// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct SimpleBooleanConfig {
}

impl SimpleBooleanConfig {
    pub fn builder() -> SimpleBooleanConfigBuilder {
        SimpleBooleanConfigBuilder::new()
    }
}

#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct SimpleBooleanConfigBuilder {
}

impl SimpleBooleanConfigBuilder {
    /// Creates a new `SimpleBooleanConfigBuilder`.
    pub(crate) fn new() -> Self {
        Self {
        }
    }
    pub fn build(
        self,
    ) -> ::std::result::Result<SimpleBooleanConfig, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(SimpleBooleanConfig {})
    }
}
