// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetEnumInput {
    #[allow(missing_docs)] // documentation missing in model
    pub value: ::std::option::Option<crate::types::simple_enum_shape::SimpleEnumShape>,
}
impl GetEnumInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn message(
        &self,
    ) -> ::std::option::Option<&crate::types::simple_enum_shape::SimpleEnumShape> {
        self.value.as_ref()
    }
}
impl GetEnumInput {
    /// Creates a new builder-style object to manufacture [`GetEnumInput`](crate::operation::operation::GetEnumInput).
    pub fn builder() -> crate::operation::get_enum::builders::GetEnumInputBuilder {
        crate::operation::get_enum::builders::GetEnumInputBuilder::default()
    }
}

/// A builder for [`GetEnumInput`](crate::operation::operation::GetEnumInput).
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
pub struct GetEnumInputBuilder {
    pub(crate) value: ::std::option::Option<crate::types::simple_enum_shape::SimpleEnumShape>,
}
impl GetEnumInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn value(
        mut self,
        input: impl ::std::convert::Into<crate::types::simple_enum_shape::SimpleEnumShape>,
    ) -> Self {
        self.value = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_value(
        mut self,
        input: ::std::option::Option<crate::types::simple_enum_shape::SimpleEnumShape>,
    ) -> Self {
        self.value = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_value(
        &self,
    ) -> &::std::option::Option<crate::types::simple_enum_shape::SimpleEnumShape> {
        &self.value
    }
    /// Consumes the builder and constructs a [`GetEnumInput`](crate::operation::operation::GetEnumInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_enum::GetEnumInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::get_enum::GetEnumInput { value: self.value })
    }
}
