# Code generated by smithy-python-codegen DO NOT EDIT.

from com_amazonaws_dynamodb_internaldafny_types import (
    BatchExecuteStatementInput_BatchExecuteStatementInput as DafnyBatchExecuteStatementInput,
    BatchGetItemInput_BatchGetItemInput as DafnyBatchGetItemInput,
    BatchWriteItemInput_BatchWriteItemInput as DafnyBatchWriteItemInput,
    CreateBackupInput_CreateBackupInput as DafnyCreateBackupInput,
    CreateGlobalTableInput_CreateGlobalTableInput as DafnyCreateGlobalTableInput,
    CreateTableInput_CreateTableInput as DafnyCreateTableInput,
    DeleteBackupInput_DeleteBackupInput as DafnyDeleteBackupInput,
    DeleteItemInput_DeleteItemInput as DafnyDeleteItemInput,
    DeleteTableInput_DeleteTableInput as DafnyDeleteTableInput,
    DescribeBackupInput_DescribeBackupInput as DafnyDescribeBackupInput,
    DescribeContinuousBackupsInput_DescribeContinuousBackupsInput as DafnyDescribeContinuousBackupsInput,
    DescribeContributorInsightsInput_DescribeContributorInsightsInput as DafnyDescribeContributorInsightsInput,
    DescribeEndpointsRequest_DescribeEndpointsRequest as DafnyDescribeEndpointsRequest,
    DescribeExportInput_DescribeExportInput as DafnyDescribeExportInput,
    DescribeGlobalTableInput_DescribeGlobalTableInput as DafnyDescribeGlobalTableInput,
    DescribeGlobalTableSettingsInput_DescribeGlobalTableSettingsInput as DafnyDescribeGlobalTableSettingsInput,
    DescribeImportInput_DescribeImportInput as DafnyDescribeImportInput,
    DescribeKinesisStreamingDestinationInput_DescribeKinesisStreamingDestinationInput as DafnyDescribeKinesisStreamingDestinationInput,
    DescribeLimitsInput_DescribeLimitsInput as DafnyDescribeLimitsInput,
    DescribeTableInput_DescribeTableInput as DafnyDescribeTableInput,
    DescribeTableReplicaAutoScalingInput_DescribeTableReplicaAutoScalingInput as DafnyDescribeTableReplicaAutoScalingInput,
    DescribeTimeToLiveInput_DescribeTimeToLiveInput as DafnyDescribeTimeToLiveInput,
    DisableKinesisStreamingDestinationInput_DisableKinesisStreamingDestinationInput as DafnyDisableKinesisStreamingDestinationInput,
    EnableKinesisStreamingDestinationInput_EnableKinesisStreamingDestinationInput as DafnyEnableKinesisStreamingDestinationInput,
    ExecuteStatementInput_ExecuteStatementInput as DafnyExecuteStatementInput,
    ExecuteTransactionInput_ExecuteTransactionInput as DafnyExecuteTransactionInput,
    ExportTableToPointInTimeInput_ExportTableToPointInTimeInput as DafnyExportTableToPointInTimeInput,
    GetItemInput_GetItemInput as DafnyGetItemInput,
    ImportTableInput_ImportTableInput as DafnyImportTableInput,
    ListBackupsInput_ListBackupsInput as DafnyListBackupsInput,
    ListContributorInsightsInput_ListContributorInsightsInput as DafnyListContributorInsightsInput,
    ListExportsInput_ListExportsInput as DafnyListExportsInput,
    ListGlobalTablesInput_ListGlobalTablesInput as DafnyListGlobalTablesInput,
    ListImportsInput_ListImportsInput as DafnyListImportsInput,
    ListTablesInput_ListTablesInput as DafnyListTablesInput,
    ListTagsOfResourceInput_ListTagsOfResourceInput as DafnyListTagsOfResourceInput,
    PutItemInput_PutItemInput as DafnyPutItemInput,
    QueryInput_QueryInput as DafnyQueryInput,
    RestoreTableFromBackupInput_RestoreTableFromBackupInput as DafnyRestoreTableFromBackupInput,
    RestoreTableToPointInTimeInput_RestoreTableToPointInTimeInput as DafnyRestoreTableToPointInTimeInput,
    ScanInput_ScanInput as DafnyScanInput,
    TagResourceInput_TagResourceInput as DafnyTagResourceInput,
    TransactGetItemsInput_TransactGetItemsInput as DafnyTransactGetItemsInput,
    TransactWriteItemsInput_TransactWriteItemsInput as DafnyTransactWriteItemsInput,
    UntagResourceInput_UntagResourceInput as DafnyUntagResourceInput,
    UpdateContinuousBackupsInput_UpdateContinuousBackupsInput as DafnyUpdateContinuousBackupsInput,
    UpdateContributorInsightsInput_UpdateContributorInsightsInput as DafnyUpdateContributorInsightsInput,
    UpdateGlobalTableInput_UpdateGlobalTableInput as DafnyUpdateGlobalTableInput,
    UpdateGlobalTableSettingsInput_UpdateGlobalTableSettingsInput as DafnyUpdateGlobalTableSettingsInput,
    UpdateItemInput_UpdateItemInput as DafnyUpdateItemInput,
    UpdateTableInput_UpdateTableInput as DafnyUpdateTableInput,
    UpdateTableReplicaAutoScalingInput_UpdateTableReplicaAutoScalingInput as DafnyUpdateTableReplicaAutoScalingInput,
    UpdateTimeToLiveInput_UpdateTimeToLiveInput as DafnyUpdateTimeToLiveInput,
)
import module_

from .dafny_protocol import DafnyRequest
from .models import (
    BatchExecuteStatementInput,
    BatchGetItemInput,
    BatchWriteItemInput,
    CreateBackupInput,
    CreateGlobalTableInput,
    CreateTableInput,
    DeleteBackupInput,
    DeleteItemInput,
    DeleteTableInput,
    DescribeBackupInput,
    DescribeContinuousBackupsInput,
    DescribeContributorInsightsInput,
    DescribeEndpointsRequest,
    DescribeExportInput,
    DescribeGlobalTableInput,
    DescribeGlobalTableSettingsInput,
    DescribeImportInput,
    DescribeKinesisStreamingDestinationInput,
    DescribeLimitsInput,
    DescribeTableInput,
    DescribeTableReplicaAutoScalingInput,
    DescribeTimeToLiveInput,
    DisableKinesisStreamingDestinationInput,
    EnableKinesisStreamingDestinationInput,
    ExecuteStatementInput,
    ExecuteTransactionInput,
    ExportTableToPointInTimeInput,
    GetItemInput,
    ImportTableInput,
    ListBackupsInput,
    ListContributorInsightsInput,
    ListExportsInput,
    ListGlobalTablesInput,
    ListImportsInput,
    ListTablesInput,
    ListTagsOfResourceInput,
    PutItemInput,
    QueryInput,
    RestoreTableFromBackupInput,
    RestoreTableToPointInTimeInput,
    ScanInput,
    TagResourceInput,
    TransactGetItemsInput,
    TransactWriteItemsInput,
    UntagResourceInput,
    UpdateContinuousBackupsInput,
    UpdateContributorInsightsInput,
    UpdateGlobalTableInput,
    UpdateGlobalTableSettingsInput,
    UpdateItemInput,
    UpdateTableInput,
    UpdateTableReplicaAutoScalingInput,
    UpdateTimeToLiveInput,
)
from .smithy_to_dafny import (
    SmithyToDafny_com_amazonaws_dynamodb_AttributeDefinition,
    SmithyToDafny_com_amazonaws_dynamodb_AttributeValue,
    SmithyToDafny_com_amazonaws_dynamodb_AttributeValueUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_AutoScalingPolicyUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_AutoScalingSettingsUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_AutoScalingTargetTrackingScalingPolicyConfigurationUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_BatchExecuteStatementInput,
    SmithyToDafny_com_amazonaws_dynamodb_BatchGetItemInput,
    SmithyToDafny_com_amazonaws_dynamodb_BatchStatementRequest,
    SmithyToDafny_com_amazonaws_dynamodb_BatchWriteItemInput,
    SmithyToDafny_com_amazonaws_dynamodb_Condition,
    SmithyToDafny_com_amazonaws_dynamodb_ConditionCheck,
    SmithyToDafny_com_amazonaws_dynamodb_CreateBackupInput,
    SmithyToDafny_com_amazonaws_dynamodb_CreateGlobalSecondaryIndexAction,
    SmithyToDafny_com_amazonaws_dynamodb_CreateGlobalTableInput,
    SmithyToDafny_com_amazonaws_dynamodb_CreateReplicaAction,
    SmithyToDafny_com_amazonaws_dynamodb_CreateReplicationGroupMemberAction,
    SmithyToDafny_com_amazonaws_dynamodb_CreateTableInput,
    SmithyToDafny_com_amazonaws_dynamodb_CsvOptions,
    SmithyToDafny_com_amazonaws_dynamodb_Delete,
    SmithyToDafny_com_amazonaws_dynamodb_DeleteBackupInput,
    SmithyToDafny_com_amazonaws_dynamodb_DeleteGlobalSecondaryIndexAction,
    SmithyToDafny_com_amazonaws_dynamodb_DeleteItemInput,
    SmithyToDafny_com_amazonaws_dynamodb_DeleteReplicaAction,
    SmithyToDafny_com_amazonaws_dynamodb_DeleteReplicationGroupMemberAction,
    SmithyToDafny_com_amazonaws_dynamodb_DeleteRequest,
    SmithyToDafny_com_amazonaws_dynamodb_DeleteTableInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeBackupInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeContinuousBackupsInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeContributorInsightsInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeEndpointsRequest,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeExportInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeGlobalTableInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeGlobalTableSettingsInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeImportInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeKinesisStreamingDestinationInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeLimitsInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeTableInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeTableReplicaAutoScalingInput,
    SmithyToDafny_com_amazonaws_dynamodb_DescribeTimeToLiveInput,
    SmithyToDafny_com_amazonaws_dynamodb_DisableKinesisStreamingDestinationInput,
    SmithyToDafny_com_amazonaws_dynamodb_EnableKinesisStreamingDestinationInput,
    SmithyToDafny_com_amazonaws_dynamodb_ExecuteStatementInput,
    SmithyToDafny_com_amazonaws_dynamodb_ExecuteTransactionInput,
    SmithyToDafny_com_amazonaws_dynamodb_ExpectedAttributeValue,
    SmithyToDafny_com_amazonaws_dynamodb_ExportTableToPointInTimeInput,
    SmithyToDafny_com_amazonaws_dynamodb_Get,
    SmithyToDafny_com_amazonaws_dynamodb_GetItemInput,
    SmithyToDafny_com_amazonaws_dynamodb_GlobalSecondaryIndex,
    SmithyToDafny_com_amazonaws_dynamodb_GlobalSecondaryIndexAutoScalingUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_GlobalSecondaryIndexUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_GlobalTableGlobalSecondaryIndexSettingsUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_ImportTableInput,
    SmithyToDafny_com_amazonaws_dynamodb_InputFormatOptions,
    SmithyToDafny_com_amazonaws_dynamodb_KeySchemaElement,
    SmithyToDafny_com_amazonaws_dynamodb_KeysAndAttributes,
    SmithyToDafny_com_amazonaws_dynamodb_ListBackupsInput,
    SmithyToDafny_com_amazonaws_dynamodb_ListContributorInsightsInput,
    SmithyToDafny_com_amazonaws_dynamodb_ListExportsInput,
    SmithyToDafny_com_amazonaws_dynamodb_ListGlobalTablesInput,
    SmithyToDafny_com_amazonaws_dynamodb_ListImportsInput,
    SmithyToDafny_com_amazonaws_dynamodb_ListTablesInput,
    SmithyToDafny_com_amazonaws_dynamodb_ListTagsOfResourceInput,
    SmithyToDafny_com_amazonaws_dynamodb_LocalSecondaryIndex,
    SmithyToDafny_com_amazonaws_dynamodb_ParameterizedStatement,
    SmithyToDafny_com_amazonaws_dynamodb_PointInTimeRecoverySpecification,
    SmithyToDafny_com_amazonaws_dynamodb_Projection,
    SmithyToDafny_com_amazonaws_dynamodb_ProvisionedThroughput,
    SmithyToDafny_com_amazonaws_dynamodb_ProvisionedThroughputOverride,
    SmithyToDafny_com_amazonaws_dynamodb_Put,
    SmithyToDafny_com_amazonaws_dynamodb_PutItemInput,
    SmithyToDafny_com_amazonaws_dynamodb_PutRequest,
    SmithyToDafny_com_amazonaws_dynamodb_QueryInput,
    SmithyToDafny_com_amazonaws_dynamodb_Replica,
    SmithyToDafny_com_amazonaws_dynamodb_ReplicaAutoScalingUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_ReplicaGlobalSecondaryIndex,
    SmithyToDafny_com_amazonaws_dynamodb_ReplicaGlobalSecondaryIndexAutoScalingUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_ReplicaGlobalSecondaryIndexSettingsUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_ReplicaSettingsUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_ReplicaUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_ReplicationGroupUpdate,
    SmithyToDafny_com_amazonaws_dynamodb_RestoreTableFromBackupInput,
    SmithyToDafny_com_amazonaws_dynamodb_RestoreTableToPointInTimeInput,
    SmithyToDafny_com_amazonaws_dynamodb_S3BucketSource,
    SmithyToDafny_com_amazonaws_dynamodb_SSESpecification,
    SmithyToDafny_com_amazonaws_dynamodb_ScanInput,
    SmithyToDafny_com_amazonaws_dynamodb_StreamSpecification,
    SmithyToDafny_com_amazonaws_dynamodb_TableCreationParameters,
    SmithyToDafny_com_amazonaws_dynamodb_Tag,
    SmithyToDafny_com_amazonaws_dynamodb_TagResourceInput,
    SmithyToDafny_com_amazonaws_dynamodb_TimeToLiveSpecification,
    SmithyToDafny_com_amazonaws_dynamodb_TransactGetItem,
    SmithyToDafny_com_amazonaws_dynamodb_TransactGetItemsInput,
    SmithyToDafny_com_amazonaws_dynamodb_TransactWriteItem,
    SmithyToDafny_com_amazonaws_dynamodb_TransactWriteItemsInput,
    SmithyToDafny_com_amazonaws_dynamodb_UntagResourceInput,
    SmithyToDafny_com_amazonaws_dynamodb_Update,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateContinuousBackupsInput,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateContributorInsightsInput,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateGlobalSecondaryIndexAction,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateGlobalTableInput,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateGlobalTableSettingsInput,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateItemInput,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateReplicationGroupMemberAction,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateTableInput,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateTableReplicaAutoScalingInput,
    SmithyToDafny_com_amazonaws_dynamodb_UpdateTimeToLiveInput,
    SmithyToDafny_com_amazonaws_dynamodb_WriteRequest,
)

from .config import Config


async def _serialize_delete_backup(input: DeleteBackupInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DeleteBackup", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DeleteBackupInput(input))

async def _serialize_delete_item(input: DeleteItemInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DeleteItem", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DeleteItemInput(input))

async def _serialize_execute_transaction(input: ExecuteTransactionInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ExecuteTransaction", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ExecuteTransactionInput(input))

async def _serialize_update_global_table(input: UpdateGlobalTableInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UpdateGlobalTable", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UpdateGlobalTableInput(input))

async def _serialize_update_table_replica_auto_scaling(input: UpdateTableReplicaAutoScalingInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UpdateTableReplicaAutoScaling", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UpdateTableReplicaAutoScalingInput(input))

async def _serialize_describe_backup(input: DescribeBackupInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeBackup", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeBackupInput(input))

async def _serialize_scan(input: ScanInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="Scan", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ScanInput(input))

async def _serialize_update_global_table_settings(input: UpdateGlobalTableSettingsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UpdateGlobalTableSettings", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UpdateGlobalTableSettingsInput(input))

async def _serialize_batch_get_item(input: BatchGetItemInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="BatchGetItem", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_BatchGetItemInput(input))

async def _serialize_describe_table(input: DescribeTableInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeTable", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeTableInput(input))

async def _serialize_query(input: QueryInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="Query", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_QueryInput(input))

async def _serialize_describe_table_replica_auto_scaling(input: DescribeTableReplicaAutoScalingInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeTableReplicaAutoScaling", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeTableReplicaAutoScalingInput(input))

async def _serialize_put_item(input: PutItemInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="PutItem", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_PutItemInput(input))

async def _serialize_disable_kinesis_streaming_destination(input: DisableKinesisStreamingDestinationInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DisableKinesisStreamingDestination", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DisableKinesisStreamingDestinationInput(input))

async def _serialize_batch_write_item(input: BatchWriteItemInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="BatchWriteItem", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_BatchWriteItemInput(input))

async def _serialize_untag_resource(input: UntagResourceInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UntagResource", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UntagResourceInput(input))

async def _serialize_tag_resource(input: TagResourceInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="TagResource", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_TagResourceInput(input))

async def _serialize_batch_execute_statement(input: BatchExecuteStatementInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="BatchExecuteStatement", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_BatchExecuteStatementInput(input))

async def _serialize_list_tags_of_resource(input: ListTagsOfResourceInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ListTagsOfResource", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ListTagsOfResourceInput(input))

async def _serialize_list_tables(input: ListTablesInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ListTables", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ListTablesInput(input))

async def _serialize_describe_export(input: DescribeExportInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeExport", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeExportInput(input))

async def _serialize_describe_time_to_live(input: DescribeTimeToLiveInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeTimeToLive", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeTimeToLiveInput(input))

async def _serialize_transact_get_items(input: TransactGetItemsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="TransactGetItems", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_TransactGetItemsInput(input))

async def _serialize_list_contributor_insights(input: ListContributorInsightsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ListContributorInsights", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ListContributorInsightsInput(input))

async def _serialize_describe_contributor_insights(input: DescribeContributorInsightsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeContributorInsights", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeContributorInsightsInput(input))

async def _serialize_update_contributor_insights(input: UpdateContributorInsightsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UpdateContributorInsights", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UpdateContributorInsightsInput(input))

async def _serialize_list_global_tables(input: ListGlobalTablesInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ListGlobalTables", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ListGlobalTablesInput(input))

async def _serialize_list_exports(input: ListExportsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ListExports", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ListExportsInput(input))

async def _serialize_list_backups(input: ListBackupsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ListBackups", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ListBackupsInput(input))

async def _serialize_enable_kinesis_streaming_destination(input: EnableKinesisStreamingDestinationInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="EnableKinesisStreamingDestination", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_EnableKinesisStreamingDestinationInput(input))

async def _serialize_export_table_to_point_in_time(input: ExportTableToPointInTimeInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ExportTableToPointInTime", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ExportTableToPointInTimeInput(input))

async def _serialize_describe_endpoints(input: DescribeEndpointsRequest, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeEndpoints", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeEndpointsRequest(input))

async def _serialize_update_time_to_live(input: UpdateTimeToLiveInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UpdateTimeToLive", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UpdateTimeToLiveInput(input))

async def _serialize_list_imports(input: ListImportsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ListImports", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ListImportsInput(input))

async def _serialize_delete_table(input: DeleteTableInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DeleteTable", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DeleteTableInput(input))

async def _serialize_restore_table_from_backup(input: RestoreTableFromBackupInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="RestoreTableFromBackup", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_RestoreTableFromBackupInput(input))

async def _serialize_describe_global_table_settings(input: DescribeGlobalTableSettingsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeGlobalTableSettings", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeGlobalTableSettingsInput(input))

async def _serialize_describe_limits(input: DescribeLimitsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeLimits", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeLimitsInput(input))

async def _serialize_restore_table_to_point_in_time(input: RestoreTableToPointInTimeInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="RestoreTableToPointInTime", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_RestoreTableToPointInTimeInput(input))

async def _serialize_get_item(input: GetItemInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="GetItem", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_GetItemInput(input))

async def _serialize_update_table(input: UpdateTableInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UpdateTable", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UpdateTableInput(input))

async def _serialize_update_item(input: UpdateItemInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UpdateItem", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UpdateItemInput(input))

async def _serialize_describe_import(input: DescribeImportInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeImport", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeImportInput(input))

async def _serialize_describe_global_table(input: DescribeGlobalTableInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeGlobalTable", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeGlobalTableInput(input))

async def _serialize_transact_write_items(input: TransactWriteItemsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="TransactWriteItems", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_TransactWriteItemsInput(input))

async def _serialize_update_continuous_backups(input: UpdateContinuousBackupsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="UpdateContinuousBackups", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_UpdateContinuousBackupsInput(input))

async def _serialize_create_backup(input: CreateBackupInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="CreateBackup", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_CreateBackupInput(input))

async def _serialize_import_table(input: ImportTableInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ImportTable", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ImportTableInput(input))

async def _serialize_describe_kinesis_streaming_destination(input: DescribeKinesisStreamingDestinationInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeKinesisStreamingDestination", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeKinesisStreamingDestinationInput(input))

async def _serialize_create_global_table(input: CreateGlobalTableInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="CreateGlobalTable", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_CreateGlobalTableInput(input))

async def _serialize_execute_statement(input: ExecuteStatementInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="ExecuteStatement", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_ExecuteStatementInput(input))

async def _serialize_create_table(input: CreateTableInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="CreateTable", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_CreateTableInput(input))

async def _serialize_describe_continuous_backups(input: DescribeContinuousBackupsInput, config: Config) -> DafnyRequest:
    return DafnyRequest(operation_name="DescribeContinuousBackups", dafny_operation_input=SmithyToDafny_com_amazonaws_dynamodb_DescribeContinuousBackupsInput(input))
