// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

use aws_smithy_types::error::operation::BuildError;

#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct Client {
    pub(crate) dafny_client: ::dafny_runtime::Object<dyn ::simple_extendable_dafny::r#_simple_dextendable_dresources_dinternaldafny_dtypes::ISimpleExtendableResourcesClient>
}

impl Client {
    /// Creates a new client from the service [`Config`](crate::Config).
    #[track_caller]
    pub fn from_conf(
        conf: crate::types::simple_extendable_resources_config::SimpleExtendableResourcesConfig,
    ) -> Result<Self, BuildError> {
        let inner =
            ::simple_extendable_dafny::_simple_dextendable_dresources_dinternaldafny::_default::SimpleExtendableResources(
                &crate::conversions::simple_extendable_resources_config::_simple_extendable_resources_config::to_dafny(
                    conf,
                ),
            );
        if matches!(
            inner.as_ref(),
            ::simple_extendable_dafny::_Wrappers_Compile::Result::Failure { .. }
        ) {
            // TODO: convert error - the potential types are not modeled!
            return Err(BuildError::other(
                ::aws_smithy_types::error::metadata::ErrorMetadata::builder()
                    .message("Invalid client config")
                    .build(),
            ));
        }
        Ok(Self {
            dafny_client: ::dafny_runtime::UpcastTo::<dafny_runtime::Object<(dyn ::simple_extendable_dafny::r#_simple_dextendable_dresources_dinternaldafny_dtypes::ISimpleExtendableResourcesClient + 'static)>>::upcast_to(inner.Extract()),
        })
    }
}

mod create_extendable_resource;
