// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

use aws_smithy_types::error::operation::BuildError;

#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct Client {
    pub(crate) dafny_client: ::dafny_runtime::Object<dyn ::simple_enum_dafny::r#_simple_dtypes_dsmithyenum_dinternaldafny_dtypes::ISimpleTypesEnumClient>
}

impl Client {
    /// Creates a new client from the service [`Config`](crate::Config).
    #[track_caller]
    pub fn from_conf(
        conf: crate::types::simple_enum_config::SimpleEnumConfig,
    ) -> Result<Self, BuildError> {
        let inner =
            ::simple_enum_dafny::_simple_dtypes_dsmithyenum_dinternaldafny::_default::SimpleEnum(
                &crate::conversions::simple_enum_config::_simple_enum_config::to_dafny(conf),
            );
        if matches!(
            inner.as_ref(),
            ::simple_enum_dafny::_Wrappers_Compile::Result::Failure { .. }
        ) {
            // TODO: convert error - the potential types are not modeled!
            return Err(BuildError::other(
                ::aws_smithy_types::error::metadata::ErrorMetadata::builder()
                    .message("Invalid client config")
                    .build(),
            ));
        }
        Ok(Self {
            dafny_client: ::dafny_runtime::upcast_object()(inner.Extract()),
        })
    }
}

mod get_enum;

mod get_enum_first_known_value_test;
mod get_enum_second_known_value_test;
mod get_enum_third_known_value_test;
