// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct SimpleExtendableResourcesConfig {}

impl SimpleExtendableResourcesConfig {
    pub fn builder() -> SimpleExtendableResourcesConfigBuilder {
        SimpleExtendableResourcesConfigBuilder::new()
    }
}

#[derive(::std::clone::Clone, ::std::fmt::Debug, ::std::default::Default)]
pub struct SimpleExtendableResourcesConfigBuilder {}

impl SimpleExtendableResourcesConfigBuilder {
    /// Creates a new `SimpleExtendableResourcesConfigBuilder`.
    pub(crate) fn new() -> Self {
        Self::default()
    }
    pub fn build(
        self,
    ) -> ::std::result::Result<
        SimpleExtendableResourcesConfig,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(SimpleExtendableResourcesConfig {})
    }
}
