// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]

pub fn to_dafny(
    value: crate::types::simple_documentation_config::SimpleDocumentationConfig
) -> ::std::rc::Rc<
    crate::implementation_from_dafny::_simple_ddocumentation_dinternaldafny_dtypes::SimpleDocumentationConfig,
>{
    ::std::rc::Rc::new(crate::implementation_from_dafny::r#_simple_ddocumentation_dinternaldafny_dtypes::SimpleDocumentationConfig::SimpleDocumentationConfig {})
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::implementation_from_dafny::r#_simple_ddocumentation_dinternaldafny_dtypes::SimpleDocumentationConfig,
    >,
) -> crate::types::simple_documentation_config::SimpleDocumentationConfig {
    crate::types::simple_documentation_config::SimpleDocumentationConfig {}
}
