# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.boolean

# TODO: Do I need PYTHON_MODULE_NAME?
# I believe I need this for Python...
# Python is unique because the project is installed as a pip module,
# and we must define the pip module name somewhere...
# This may just be the library name located at src/... can I pipe this in from there...?
PYTHON_MODULE_NAME=simple_boolean

# This project has no dependencies 
# DEPENDENT-MODELS:= 
# LIBRARIES :=
