# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.boolean
# I believe I need this for Python...
# Python may be unique because the project is installed as a pip module,
# and we must define the pip module name somewhere
PYTHON_MODULE_NAME=simple_boolean

# This project has no dependencies 
# DEPENDENT-MODELS:= 
# LIBRARIES :=
