// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]

pub fn to_dafny(
    value: crate::types::simple_errors_config::SimpleErrorsConfig,
) -> ::std::rc::Rc<::simple_errors_dafny::_simple_derrors_dinternaldafny_dtypes::SimpleErrorsConfig>
{
    ::std::rc::Rc::new(::simple_errors_dafny::r#_simple_derrors_dinternaldafny_dtypes::SimpleErrorsConfig::SimpleErrorsConfig {})
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        ::simple_errors_dafny::r#_simple_derrors_dinternaldafny_dtypes::SimpleErrorsConfig,
    >,
) -> crate::types::simple_errors_config::SimpleErrorsConfig {
    crate::types::simple_errors_config::SimpleErrorsConfig {}
}
