// Code generated by smithy-go-codegen DO NOT EDIT.

package simplecallingawssdkfromlocalservicesmithygenerated

import (
	"github.com/smithy-lang/smithy-dafny/TestModels/CallingAWSSDKFromLocalService/SimpleCallingawssdkfromlocalserviceTypes"
	"github.com/dafny-lang/DafnyStandardLibGo/Wrappers"
	"github.com/smithy-lang/smithy-dafny/ddb/comamazonawsdynamodbsmithygenerated"
	"github.com/smithy-lang/smithy-dafny/kms/comamazonawskmssmithygenerated"
	"github.com/dafny-lang/DafnyRuntimeGo/dafny"
	"github.com/smithy-lang/smithy-dafny/TestModels/CallingAWSSDKFromLocalService/simplecallingawssdkfromlocalservicesmithygeneratedtypes"
)

func CallDDBScanInput_ToDafny(nativeInput simplecallingawssdkfromlocalservicesmithygeneratedtypes.CallDDBScanInput)(SimpleCallingawssdkfromlocalserviceTypes.CallDDBScanInput) {

    return func () SimpleCallingawssdkfromlocalserviceTypes.CallDDBScanInput {

        return SimpleCallingawssdkfromlocalserviceTypes.Companion_CallDDBScanInput_.Create_CallDDBScanInput_(nativeInput.DdbClient,simple_callingawssdkfromlocalservice_CallDDBScanInput_tableArn_ToDafny(nativeInput.TableArn),)
    }()

}

func CallDDBScanOutput_ToDafny(nativeOutput simplecallingawssdkfromlocalservicesmithygeneratedtypes.CallDDBScanOutput)(SimpleCallingawssdkfromlocalserviceTypes.CallDDBScanOutput) {

    return func () SimpleCallingawssdkfromlocalserviceTypes.CallDDBScanOutput {

        return SimpleCallingawssdkfromlocalserviceTypes.Companion_CallDDBScanOutput_.Create_CallDDBScanOutput_(simple_callingawssdkfromlocalservice_CallDDBScanOutput_itemOutput_ToDafny(nativeOutput.ItemOutput),)
    }()

}

func CallKMSEncryptInput_ToDafny(nativeInput simplecallingawssdkfromlocalservicesmithygeneratedtypes.CallKMSEncryptInput)(SimpleCallingawssdkfromlocalserviceTypes.CallKMSEncryptInput) {

    return func () SimpleCallingawssdkfromlocalserviceTypes.CallKMSEncryptInput {

        return SimpleCallingawssdkfromlocalserviceTypes.Companion_CallKMSEncryptInput_.Create_CallKMSEncryptInput_(nativeInput.KmsClient,simple_callingawssdkfromlocalservice_CallKMSEncryptInput_keyId_ToDafny(nativeInput.KeyId),simple_callingawssdkfromlocalservice_CallKMSEncryptInput_plaintext_ToDafny(nativeInput.Plaintext),)
    }()

}

func CallKMSEncryptOutput_ToDafny(nativeOutput simplecallingawssdkfromlocalservicesmithygeneratedtypes.CallKMSEncryptOutput)(SimpleCallingawssdkfromlocalserviceTypes.CallKMSEncryptOutput) {

    return func () SimpleCallingawssdkfromlocalserviceTypes.CallKMSEncryptOutput {

        return SimpleCallingawssdkfromlocalserviceTypes.Companion_CallKMSEncryptOutput_.Create_CallKMSEncryptOutput_(simple_callingawssdkfromlocalservice_CallKMSEncryptOutput_encryptOutput_ToDafny(nativeOutput.EncryptOutput),)
    }()

}

func SimpleCallingAWSSDKFromLocalServiceException_ToDafny(nativeInput simplecallingawssdkfromlocalservicesmithygeneratedtypes.SimpleCallingAWSSDKFromLocalServiceException)(SimpleCallingawssdkfromlocalserviceTypes.Error) {
    return func () SimpleCallingawssdkfromlocalserviceTypes.Error {

        return SimpleCallingawssdkfromlocalserviceTypes.Companion_Error_.Create_SimpleCallingAWSSDKFromLocalServiceException_(simple_callingawssdkfromlocalservice_SimpleCallingAWSSDKFromLocalServiceException_message_ToDafny(nativeInput.Message),)
    }()

}

func CollectionOfErrors_Input_ToDafny(nativeInput simplecallingawssdkfromlocalservicesmithygeneratedtypes.CollectionOfErrors)(SimpleCallingawssdkfromlocalserviceTypes.Error) {
	var e []interface{}
	for _, i2 := range nativeInput.ListOfErrors {
       e = append(e, Error_ToDafny(i2))
	}
	return SimpleCallingawssdkfromlocalserviceTypes.Companion_Error_.Create_CollectionOfErrors_(dafny.SeqOf(e...), dafny.SeqOfChars([]dafny.Char(nativeInput.Message)...))
}
func OpaqueError_Input_ToDafny(nativeInput simplecallingawssdkfromlocalservicesmithygeneratedtypes.OpaqueError)(SimpleCallingawssdkfromlocalserviceTypes.Error) {
	return SimpleCallingawssdkfromlocalserviceTypes.Companion_Error_.Create_Opaque_(nativeInput.ErrObject)
}

func Error_ToDafny(err error)(SimpleCallingawssdkfromlocalserviceTypes.Error) {
    switch err.(type) {
    // Service Errors
      case simplecallingawssdkfromlocalservicesmithygeneratedtypes.SimpleCallingAWSSDKFromLocalServiceException:
          return SimpleCallingAWSSDKFromLocalServiceException_ToDafny(err.(simplecallingawssdkfromlocalservicesmithygeneratedtypes.SimpleCallingAWSSDKFromLocalServiceException))

    //DependentErrors
    case smithy.APIError:
    kmsError := comamazonawskmssmithygenerated.Error_ToDafny(err)
      // There is no generic way to know if the error is a kms or a ddb error. So, we check for Opaque error.
      if(kmsError.Is_Opaque()) {
        ddbError := comamazonawsdynamodbsmithygenerated.Error_ToDafny(err)
        return SimpleCallingawssdkfromlocalserviceTypes.Companion_Error_.Create_ComAmazonawsDynamodb_(ddbError)
      } else {
        return SimpleCallingawssdkfromlocalserviceTypes.Companion_Error_.Create_ComAmazonawsKms_(kmsError)
      }

    //Unmodelled Errors
    case simplecallingawssdkfromlocalservicesmithygeneratedtypes.CollectionOfErrors:
        return CollectionOfErrors_Input_ToDafny(err.(simplecallingawssdkfromlocalservicesmithygeneratedtypes.CollectionOfErrors))

    default:
        error, ok := err.(simplecallingawssdkfromlocalservicesmithygeneratedtypes.OpaqueError)
        if !ok {
          // We expect to get error string for opaque error from SDK error
          error = simplecallingawssdkfromlocalservicesmithygeneratedtypes.OpaqueError{ErrObject: err}
        }
        return OpaqueError_Input_ToDafny(error)
    }
}

func SimpleCallingAWSSDKFromLocalServiceConfig_ToDafny(nativeInput simplecallingawssdkfromlocalservicesmithygeneratedtypes.SimpleCallingAWSSDKFromLocalServiceConfig)(SimpleCallingawssdkfromlocalserviceTypes.SimpleCallingAWSSDKFromLocalServiceConfig) {
    return func () SimpleCallingawssdkfromlocalserviceTypes.SimpleCallingAWSSDKFromLocalServiceConfig {

        return SimpleCallingawssdkfromlocalserviceTypes.Companion_SimpleCallingAWSSDKFromLocalServiceConfig_.Create_SimpleCallingAWSSDKFromLocalServiceConfig_()
    }()

}

func simple_callingawssdkfromlocalservice_CallKMSEncryptInput_keyId_ToDafny(input string)(dafny.Sequence) {
    return func () dafny.Sequence {

    return dafny.SeqOfChars([]dafny.Char(input)...)
}()
}

func simple_callingawssdkfromlocalservice_SimpleCallingAWSSDKFromLocalServiceException_message_ToDafny(input string)(dafny.Sequence) {
    return func () dafny.Sequence {

    return dafny.SeqOfChars([]dafny.Char(input)...)
}()
}

func simple_callingawssdkfromlocalservice_CallDDBScanInput_tableArn_ToDafny(input string)(dafny.Sequence) {
    return func () dafny.Sequence {

    return dafny.SeqOfChars([]dafny.Char(input)...)
}()
}

func simple_callingawssdkfromlocalservice_CallDDBScanOutput_itemOutput_ToDafny(input int32)(int32) {
    return func () int32 {

    return input
}()
}

func simple_callingawssdkfromlocalservice_CallKMSEncryptOutput_encryptOutput_ToDafny(input string)(dafny.Sequence) {
    return func () dafny.Sequence {

    return dafny.SeqOfChars([]dafny.Char(input)...)
}()
}

func simple_callingawssdkfromlocalservice_CallKMSEncryptInput_plaintext_ToDafny(input []byte)(dafny.Sequence) {
    return func () dafny.Sequence {
    var v []interface{}
    if input == nil {return nil}
    for _, e := range input {
    	v = append(v, e)
    }
    return dafny.SeqOf(v...);
}()
}
