// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]
pub fn to_dafny(
    value: &aws_sdk_kms::operation::decrypt::DecryptOutput
) -> ::std::rc::Rc<
    crate::r#software::amazon::cryptography::services::kms::internaldafny::types::DecryptResponse,
> {
    ::std::rc::Rc::new(crate::r#software::amazon::cryptography::services::kms::internaldafny::types::DecryptResponse::DecryptResponse { 
      Plaintext: crate::standard_library_conversions::oblob_to_dafny(&value.plaintext),
      KeyId: crate::standard_library_conversions::ostring_to_dafny(&value.key_id),
      CiphertextForRecipient: crate::standard_library_conversions::oblob_to_dafny(&value.ciphertext_for_recipient),
      EncryptionAlgorithm: crate::standard_library_conversions::option_to_dafny(&value.encryption_algorithm,
        |x| crate::conversions::encryption_algorithm_spec::to_dafny(x.clone())),
    })
}

// from_dafny ommitted to save time until we get to actual code generation
