// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]
pub fn to_dafny(
    value: aws_sdk_kms::operation::decrypt::DecryptInput
) -> ::std::rc::Rc<
    crate::r#software::amazon::cryptography::services::kms::internaldafny::types::DecryptRequest,
>{
    ::std::rc::Rc::new(crate::r#software::amazon::cryptography::services::kms::internaldafny::types::DecryptRequest::DecryptRequest  {
        CiphertextBlob: crate::standard_library_conversions::oblob_to_dafny(&value.ciphertext_blob).Extract(), 
        KeyId: crate::standard_library_conversions::ostring_to_dafny(&value.key_id),
        EncryptionContext: 
        ::std::rc::Rc::new(match value.encryption_context() {
            Some(x) => crate::r#_Wrappers_Compile::Option::Some { value :
                ::dafny_runtime::dafny_runtime_conversions::hashmap_to_dafny_map(x,
                    |k| dafny_runtime::dafny_runtime_conversions::unicode_chars_false::string_to_dafny_string(k),
                    |v| dafny_runtime::dafny_runtime_conversions::unicode_chars_false::string_to_dafny_string(v),
                )
            },
            None => crate::r#_Wrappers_Compile::Option::None {}
        }),
        GrantTokens:
        ::std::rc::Rc::new(
            // Have to clone or else this becomes a borrow that can interfere with other branches
            match value.grant_tokens.clone() {
                Some(val) =>
                crate::r#_Wrappers_Compile::Option::Some {
                        value : ::dafny_runtime::Sequence::from_array(
                            &val.iter().map(|x|
                                dafny_runtime::dafny_runtime_conversions::unicode_chars_false::string_to_dafny_string(x))
                                .collect()
                        )
                    },
                None => crate::r#_Wrappers_Compile::Option::None{}
            }
        ),
        Recipient: crate::conversions::recipient_info::option_to_dafny(value.recipient()),
        DryRun: crate::standard_library_conversions::obool_to_dafny(value.dry_run),
        EncryptionAlgorithm: ::std::rc::Rc::new(match value.encryption_algorithm {
            Some(x) => crate::_Wrappers_Compile::Option::Some { value: crate::conversions::encryption_algorithm_spec::to_dafny(x) },
            None => crate::_Wrappers_Compile::Option::None { }
        })
    })
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
    crate::r#software::amazon::cryptography::services::kms::internaldafny::types::DecryptRequest,
    >,
    client: aws_sdk_kms::Client,
) -> aws_sdk_kms::operation::decrypt::builders::DecryptFluentBuilder {
    client.decrypt()
        .set_ciphertext_blob(Some(
            crate::standard_library_conversions::blob_from_dafny(dafny_value.CiphertextBlob().clone())))
        .set_key_id(
            crate::standard_library_conversions::ostring_from_dafny(dafny_value.KeyId().clone()),
        )
        .set_encryption_context( match (*dafny_value.EncryptionContext()).as_ref() {
            crate::r#_Wrappers_Compile::Option::Some { value } =>
                Some(
                    ::dafny_runtime::dafny_runtime_conversions::dafny_map_to_hashmap(value,
                        dafny_runtime::dafny_runtime_conversions::unicode_chars_false::dafny_string_to_string,
                        dafny_runtime::dafny_runtime_conversions::unicode_chars_false::dafny_string_to_string,
                    )
                ),
            _ => None
        })
        .set_grant_tokens(match  &**dafny_value.GrantTokens() {
            crate::r#_Wrappers_Compile::Option::Some { value } =>
                Some(
                    ::dafny_runtime::dafny_runtime_conversions::dafny_sequence_to_vec(value, 
                        dafny_runtime::dafny_runtime_conversions::unicode_chars_false::dafny_string_to_string)
                ),
            _ => None
        })
        .set_recipient(match  &**dafny_value.Recipient() {
            crate::r#_Wrappers_Compile::Option::Some { value } =>
                Some(
                    crate::conversions::recipient_info::from_dafny(value.clone())
                ),
            _ => None
        })
        .set_dry_run(crate::standard_library_conversions::obool_from_dafny(dafny_value.DryRun().clone()))
        .set_encryption_algorithm(
            crate::standard_library_conversions::option_from_dafny(
                dafny_value.EncryptionAlgorithm().clone(), 
                |x| crate::conversions::encryption_algorithm_spec::from_dafny(x)))
}
