// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Types for the `GetDouble` operation.
pub mod get_double;

/// Types for the `GetDoubleKnownValue` operation.
pub mod get_double_known_value;
