// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetAggregateKnownValueTest`](crate::operation::get_aggregate_known_value::builders::GetAggregateKnownValueTestFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`value(impl Into<Option<String>>)`](crate::operation::get_aggregate_known_value::builders::GetAggregateKnownValueTestFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::get_aggregate_known_value::builders::GetAggregateKnownValueTestFluentBuilder::set_name):(undocumented)<br>
    /// - On success, responds with [`GetAggregateKnownValueTestOutput`](crate::operation::get_aggregate_known_value::GetAggregateKnownValueTestOutput) with field(s):
    ///   - [`value(Option<String>)`](crate::operation::get_aggregate_known_value::GetAggregateKnownValueTestOutput::value): (undocumented)
    /// - On failure, responds with [`SdkError<GetAggregateKnownValueTestError>`](crate::operation::get_aggregate_known_value::GetAggregateKnownValueTestError)
    pub fn get_aggregate_known_value_test(
        &self,
    ) -> crate::operation::get_aggregate_known_value_test::builders::GetAggregateKnownValueTestFluentBuilder{
        crate::operation::get_aggregate_known_value_test::builders::GetAggregateKnownValueTestFluentBuilder::new(
            self.clone(),
        )
    }
}
