# Code generated by smithy-python-codegen DO NOT EDIT.

from typing import TypeVar

from smithy_python._private.http import set_static_endpoint_resolver

from .config import Config, Plugin
from .models import GetBooleanInput, GetBooleanOutput


Input = TypeVar("Input")
Output = TypeVar("Output")

class SimpleTypesBoolean:
    """Client for SimpleTypesBoolean

    :param config: Optional configuration for the client. Here you can set things like the
    endpoint for HTTP services or auth credentials.

    :param plugins: A list of callables that modify the configuration dynamically. These
    can be used to set defaults, for example.
    """
    def __init__(self, config: Config | None = None, plugins: list[Plugin] | None = None):
        self._config = config or Config()

        client_plugins: list[Plugin] = [
            set_static_endpoint_resolver,
        ]
        if plugins:
            client_plugins.extend(plugins)

        for plugin in client_plugins:
            plugin(self._config)

    async def get_boolean(self, input: GetBooleanInput, plugins: list[Plugin] | None = None) -> GetBooleanOutput:
        """Invokes the GetBoolean operation.

        :param input: The operation's input.

        :param plugins: A list of callables that modify the configuration dynamically.
        Changes made by these plugins only apply for the duration of the operation
        execution and will not affect any other operation invocations.
        """
        operation_plugins = [

        ]
        if plugins:
            operation_plugins.extend(plugins)

        raise NotImplementedError()
