// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

pub trait SimpleResource {
    fn get_resource_data(
        &mut self,
        input: crate::operation::get_resource_data::GetResourceDataInput,
    ) -> Result<
        crate::operation::get_resource_data::GetResourceDataOutput,
        crate::operation::get_resource_data::GetResourceDataError,
    >;
}

pub type SimpleResourceRef = ::std::rc::Rc<std::cell::RefCell<dyn SimpleResource>>;
