// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::get_refinement::_get_refinement_output::GetRefinementOutputBuilder;

pub use crate::operation::get_refinement::_get_refinement_input::GetRefinementInputBuilder;

impl GetRefinementInputBuilder {
    /// Sends a request with this input using the given client.
    pub async fn send_with(
        self,
        client: &crate::Client,
    ) -> ::std::result::Result<
        crate::operation::get_refinement::GetRefinementOutput,
        crate::operation::get_refinement::GetRefinementError,
    > {
        let mut fluent_builder = client.get_refinement();
        fluent_builder.inner = self;
        fluent_builder.send().await
    }
}
/// Fluent builder constructing a request to `GetRefinement`.
///
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct GetRefinementFluentBuilder {
    client: crate::client::Client,
    inner: crate::operation::get_refinement::builders::GetRefinementInputBuilder,
}
impl GetRefinementFluentBuilder {
    /// Creates a new `GetRefinement`.
    pub(crate) fn new(client: crate::client::Client) -> Self {
        Self {
            client,
            inner: ::std::default::Default::default(),
        }
    }
    /// Access the GetRefinement as a reference.
    pub fn as_input(
        &self,
    ) -> &crate::operation::get_refinement::builders::GetRefinementInputBuilder {
        &self.inner
    }
    /// Sends the request and returns the response.
    pub async fn send(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_refinement::GetRefinementOutput,
        crate::operation::get_refinement::GetRefinementError,
    > {
        let input = self
            .inner
            .build()
            // Using unhandled since GetRefinement doesn't declare any validation,
            // and smithy-rs seems to not generate a ValidationError case unless there is
            // (but isn't that a backwards compatibility problem for output structures?)
            // Vanilla smithy-rs uses SdkError::construction_failure,
            // but we aren't using SdkError.
            .map_err(crate::operation::get_refinement::GetRefinementError::unhandled)?;
        crate::operation::get_refinement::GetRefinement::send(&self.client, input).await
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn required_string(
        mut self,
        input: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        self.inner = self.inner.required_string(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_required_string(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_required_string()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn optional_string(
        mut self,
        input: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        self.inner = self.inner.optional_string(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_optional_string(
        mut self,
        input: ::std::option::Option<::std::string::String>,
    ) -> Self {
        self.inner = self.inner.set_optional_string(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_optional_string(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_optional_string()
    }
}
