# Code generated by smithy-python-codegen DO NOT EDIT.

#from Dafny.Path.To.Dafny.Code. import SimpleBooleanHardCoded as _SimpleBooleanHardCoded
from simple.types.boolean.internaldafny.types import GetBooleanInput_GetBooleanInput as DafnyGetBooleanInput

from .config import Config
from .models import GetBooleanInput


async def _serialize_get_boolean(input: GetBooleanInput, config: Config) -> DafnyGetBooleanInput:
    return DafnyGetBooleanInput(value=input.value)
