// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct SimpleDoubleConfig {}

impl SimpleDoubleConfig {
    pub fn builder() -> SimpleDoubleConfigBuilder {
        SimpleDoubleConfigBuilder::new()
    }
}

#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct SimpleDoubleConfigBuilder {}

impl SimpleDoubleConfigBuilder {
    /// Creates a new `SimpleDoubleConfigBuilder`.
    pub(crate) fn new() -> Self {
        Self {}
    }
    pub fn build(
        self,
    ) -> ::std::result::Result<SimpleDoubleConfig, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(SimpleDoubleConfig {})
    }
}
