# Code generated by smithy-python-codegen DO NOT EDIT.

from simple.errors.internaldafny.types import (
    GetErrorsInput_GetErrorsInput as DafnyGetErrorsInput,
)

from .config import Config
from .models import GetErrorsInput


async def _serialize_always_error(input: GetErrorsInput, config: Config) -> DafnyGetErrorsInput:
    return ("AlwaysError", DafnyGetErrorsInput(value=input.value))

async def _serialize_always_multiple_errors(input: GetErrorsInput, config: Config) -> DafnyGetErrorsInput:
    return ("AlwaysMultipleErrors", DafnyGetErrorsInput(value=input.value))

async def _serialize_always_native_error(input: GetErrorsInput, config: Config) -> DafnyGetErrorsInput:
    return ("AlwaysNativeError", DafnyGetErrorsInput(value=input.value))
