# Project file for easier development in VS Code.
# Not yet used in the actual Makefile build.

[options]
unicode-char = false
function-syntax = 3

library = [
  "../../dafny-dependencies/StandardLibrary/bin/DafnyStandardLibraries-smithy-dafny-subset.doo"
]
