# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../../SharedMakefile.mk

NAMESPACE=simple.types.smithyLong

PROJECT_SERVICES := \
	SimpleLong

SERVICE_NAMESPACE_SimpleLong=simple.types.smithyLong

SERVICE_DEPS_SimpleLong :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies 
# DEPENDENT-MODELS:= 

