# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.smithyLong
# TODO: Move to smithy-build.json once language-specific config is supported
PYTHON_MODULE_NAME=simple_types_smithylong

# This project has no dependencies 
# DEPENDENT-MODELS:= 
# LIBRARIES :=
