
CORES=2

USE_DAFNY_STANDARD_LIBRARIES=1

include ../../SharedMakefile.mk

transpile_java: | transpile_implementation_java transpile_test_java

transpile_python: | transpile_implementation_python transpile_test_python