// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct SimpleResourceReference {}
impl SimpleResourceReference {
    /// Creates a new builder-style object to manufacture [`SimpleResourceReference`](crate::types::SimpleResourceReference).
    pub fn builder() -> crate::types::builders::SimpleResourceReferenceBuilder {
        crate::types::builders::SimpleResourceReferenceBuilder::default()
    }
}

/// A builder for [`SimpleResourceReference`](crate::types::SimpleResourceReference).
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
pub struct SimpleResourceReferenceBuilder {}
impl SimpleResourceReferenceBuilder {
    /// Consumes the builder and constructs a [`SimpleResourceReference`](crate::types::SimpleResourceReference).
    pub fn build(self) -> crate::SimpleResourceReference {
        crate::SimpleResourceReference {}
    }
}
