// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Types for the `SimplePositionalConfig`
pub mod simple_positional_config;

pub mod _simple_resource_reference;

pub mod builders;
