// Code generated by smithy-go-codegen DO NOT EDIT.

package WrappedSimpleResources

import (
	"context"

	"github.com/aws/aws-cryptographic-material-providers-library/releases/go/smithy-dafny-standard-library/Wrappers"
	"github.com/smithy-lang/smithy-dafny/TestModels/Resource/SimpleResourcesTypes"
	"github.com/smithy-lang/smithy-dafny/TestModels/Resource/simpleresourcessmithygenerated"
)

type Shim struct {
	SimpleResourcesTypes.ISimpleResourcesClient
	client *simpleresourcessmithygenerated.Client
}

func (_static *CompanionStruct_Default___) WrappedSimpleResources(inputConfig SimpleResourcesTypes.SimpleResourcesConfig) Wrappers.Result {
	var nativeConfig = simpleresourcessmithygenerated.SimpleResourcesConfig_FromDafny(inputConfig)
	var nativeClient, nativeError = simpleresourcessmithygenerated.NewClient(nativeConfig)
	if nativeError != nil {
		return Wrappers.Companion_Result_.Create_Failure_(SimpleResourcesTypes.Companion_Error_.Create_Opaque_(nativeError))
	}
	return Wrappers.Companion_Result_.Create_Success_(&Shim{client: nativeClient})
}

func (shim *Shim) GetResources(input SimpleResourcesTypes.GetResourcesInput) Wrappers.Result {
	var native_request = simpleresourcessmithygenerated.GetResourcesInput_FromDafny(input)
	var native_response, native_error = shim.client.GetResources(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpleresourcessmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpleresourcessmithygenerated.GetResourcesOutput_ToDafny(*native_response))
}

func (shim *Shim) GetMutableResources(input SimpleResourcesTypes.GetMutableResourcesInput) Wrappers.Result {
	var native_request = simpleresourcessmithygenerated.GetMutableResourcesInput_FromDafny(input)
	var native_response, native_error = shim.client.GetMutableResources(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpleresourcessmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpleresourcessmithygenerated.GetMutableResourcesOutput_ToDafny(*native_response))
}
