// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetThingInput {
    #[allow(missing_docs)] // documentation missing in model
    pub value: ::std::option::Option<::std::primitive::bool>,
}
impl GetThingInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn value(&self) -> ::std::option::Option<bool> {
        self.value
    }
}
impl GetThingInput {
    /// Creates a new builder-style object to manufacture [`GetThingInput`](crate::operation::operation::GetThingInput).
    pub fn builder() -> crate::operation::get_thing::builders::GetThingInputBuilder {
        crate::operation::get_thing::builders::GetThingInputBuilder::default()
    }
}

/// A builder for [`GetThingInput`](crate::operation::operation::GetThingInput).
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
pub struct GetThingInputBuilder {
    pub(crate) value: ::std::option::Option<::std::primitive::bool>,
}
impl GetThingInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn value(mut self, input: impl ::std::convert::Into<::std::primitive::bool>) -> Self {
        self.value = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_value(mut self, input: ::std::option::Option<::std::primitive::bool>) -> Self {
        self.value = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_value(&self) -> &::std::option::Option<::std::primitive::bool> {
        &self.value
    }
    /// Consumes the builder and constructs a [`GetThingInput`](crate::operation::operation::GetThingInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_thing::GetThingInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::get_thing::GetThingInput { value: self.value })
    }
}
