// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]

pub fn to_dafny(
    value: crate::types::simple_integer_config::SimpleIntegerConfig,
) -> ::std::rc::Rc<
    crate::simple::types::integer::internaldafny::types::SimpleIntegerConfig,
> {
    ::std::rc::Rc::new(crate::r#simple::types::integer::internaldafny::types::SimpleIntegerConfig::SimpleIntegerConfig {})
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#simple::types::integer::internaldafny::types::SimpleIntegerConfig,
    >,
) -> crate::types::simple_integer_config::SimpleIntegerConfig {
    crate::types::simple_integer_config::SimpleIntegerConfig {}
}
