# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../SharedMakefile.mk

NAMESPACE=simple.dafnyExternV2

DOT_NAMESPACE_SRC_INDEX=src/IndexDotNamespaced.dfy
UNDERSCORE_NAMESPACE_SRC_INDEX=src/IndexUnderscoreNamespaced.dfy

DOT_NAMESPACE_TEST_INDEX=test/WrappedTestDotNamespaced.dfy
UNDERSCORE_NAMESPACE_TEST_INDEX=test/WrappedTestUnderscoreNamespaced.dfy

# This project has no dependencies 
# DEPENDENT-MODELS:= 
# LIBRARIES :=
