# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../SharedMakefile.mk

NAMESPACE=simple.dafnyExternV2
DOT_NAMESPACE_INDEX=src/IndexDotNamespaced.dfy

# This project has no dependencies 
# DEPENDENT-MODELS:= 
# LIBRARIES :=
