// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]
pub fn to_dafny(
    value: crate::operation::get_resource_positional::GetResourcePositionalOutput,
) -> ::std::rc::Rc<
    crate::implementation_from_dafny::r#_simple_dpositional_dinternaldafny_dtypes::GetResourceOutput,
>{
    let output = dafny_runtime::Object(todo!());

    ::std::rc::Rc::new(crate::implementation_from_dafny::r#_simple_dpositional_dinternaldafny_dtypes::GetResourceOutput::GetResourceOutput { output })
}

#[allow(dead_code)]
pub fn from_dafny(
    _dafny_value: ::std::rc::Rc<
    crate::implementation_from_dafny::r#_Wrappers_Compile::Result<
        ::dafny_runtime::Object<
            dyn crate::implementation_from_dafny::r#_simple_dpositional_dinternaldafny_dtypes::ISimpleResource,
            >,
        ::std::rc::Rc<crate::implementation_from_dafny::r#_simple_dpositional_dinternaldafny_dtypes::Error>,
        >
    >,
) -> crate::operation::get_resource_positional::GetResourcePositionalOutput {
    let output = crate::SimpleResourceReference {};

    crate::operation::get_resource_positional::GetResourcePositionalOutput { output }
}
