// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetStringSingleValueOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub value: ::std::option::Option<::std::string::String>,
}
impl GetStringSingleValueOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn value(&self) -> ::std::option::Option<&str> {
        self.value.as_deref()
    }
}
impl GetStringSingleValueOutput {
    /// Creates a new builder-style object to manufacture [`GetStringSingleValueOutput`](crate::operation::operation::GetStringSingleValueOutput).
    pub fn builder(
    ) -> crate::operation::get_string_single_value::builders::GetStringSingleValueOutputBuilder
    {
        crate::operation::get_string_single_value::builders::GetStringSingleValueOutputBuilder::default()
    }
}

/// A builder for [`GetStringSingleValueOutput`](crate::operation::operation::GetStringSingleValueOutput).
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
pub struct GetStringSingleValueOutputBuilder {
    pub(crate) value: ::std::option::Option<::std::string::String>,
}
impl GetStringSingleValueOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn value(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.value = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_value(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.value = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_value(&self) -> &::std::option::Option<::std::string::String> {
        &self.value
    }
    /// Consumes the builder and constructs a [`GetStringSingleValueOutput`](crate::operation::operation::GetStringSingleValueOutput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_string_single_value::GetStringSingleValueOutput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::get_string_single_value::GetStringSingleValueOutput {
                value: self.value,
            },
        )
    }
}
