# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../SharedMakefile.mk

NAMESPACE=simple.extendable.resources

# This project has no dependencies 
# DEPENDENT-MODELS:= 
# LIBRARIES :=
transpile_net_dependencies:


clean:
	rm \
	  $(PWD/)Model/*.dfy;
	  # $(PWD)/runtimes/net/ImplementationFromDafny.cs;
	  ##$(PWD)runtimes/net/tests/TestFromDafny.cs;
	# rm -rf $(PWD)/TestResults $(PWD)/runtimes/net/Generated
