# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.enumV2

# TODO-Python-PYTHONPATH: Move into dfyproject.toml
PYTHON_MODULE_NAME=simple_types_smithyenumv2

PROJECT_SERVICES := \
        SimpleTypesEnumV2

SERVICE_NAMESPACE_SimpleTypesEnumV2=simple.types.enumV2

SERVICE_DEPS_SimpleTypesEnumV2 :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies
# DEPENDENT-MODELS:=
