# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.enumV2

PROJECT_SERVICES := \
        SimpleTypesEnumV2

SERVICE_NAMESPACE_SimpleTypesEnumV2=simple.types.enumV2

SERVICE_DEPS_SimpleTypesEnumV2 :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

GO_MODULE_NAME="github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleEnumV2"

PROJECT_DTR := \
    dafny-dependencies/StandardLibrary/runtimes/go/ImplementationFromDafny-go/ImplementationFromDafny-go.dtr
# This project has no dependencies
# DEPENDENT-MODELS:=
