# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.document

PROJECT_SERVICES := \
	SimpleDocument

SERVICE_NAMESPACE_SimpleDocument=simple.types.document

SERVICE_DEPS_SimpleDocument :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies 
# DEPENDENT-MODELS:= 
# LIBRARIES :=
