# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

ENABLE_EXTERN_PROCESSING=1

include ../SharedMakefile.mk

NAMESPACE=simple.refinement

PROJECT_SERVICES := \
	SimpleRefinement

SERVICE_NAMESPACE_SimpleRefinement=simple.refinement

SERVICE_DEPS_SimpleRefinement :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies 
# DEPENDENT-MODELS:= 

