// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

mod _thing;
pub mod builders;
/// Types for the `SimpleDocumentationConfig`
pub mod simple_documentation_config;

pub use _thing::*;
