// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::create_extendable_resource::_create_extendable_resource_output::CreateExtendableResourceOutputBuilder;

pub use crate::operation::create_extendable_resource::_create_extendable_resource_input::CreateExtendableResourceInputBuilder;

impl CreateExtendableResourceInputBuilder {
    /// Sends a request with this input using the given client.
    pub async fn send_with(
        self,
        client: &crate::Client,
    ) -> ::std::result::Result<
        crate::operation::create_extendable_resource::CreateExtendableResourceOutput,
        crate::operation::create_extendable_resource::CreateExtendableResourceError,
    > {
        let mut fluent_builder = client.create_extendable_resource();
        fluent_builder.inner = self;
        fluent_builder.send().await
    }
}
/// Fluent builder constructing a request to `CreateExtendableResource`.
///
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct CreateExtendableResourceFluentBuilder {
    client: crate::client::Client,
    inner: crate::operation::create_extendable_resource::builders::CreateExtendableResourceInputBuilder,
}
impl CreateExtendableResourceFluentBuilder {
    /// Creates a new `CreateExtendableResource`.
    pub(crate) fn new(client: crate::client::Client) -> Self {
        Self {
            client,
            inner: ::std::default::Default::default(),
        }
    }
    /// Access the CreateExtendableResource as a reference.
    pub fn as_input(
        &self,
    ) -> &crate::operation::create_extendable_resource::builders::CreateExtendableResourceInputBuilder
    {
        &self.inner
    }
    /// Sends the request and returns the response.
    pub async fn send(
        self,
    ) -> ::std::result::Result<
        crate::operation::create_extendable_resource::CreateExtendableResourceOutput,
        crate::operation::create_extendable_resource::CreateExtendableResourceError,
    > {
        let input = self
            .inner
            .build()
            // Using unhandled since CreateExtendableResource doesn't declare any validation,
            // and smithy-rs seems to not generate a ValidationError case unless there is
            // (but isn't that a backwards compatibility problem for output structures?)
            // Vanilla smithy-rs uses SdkError::construction_failure,
            // but we aren't using SdkError.
            .map_err(crate::operation::create_extendable_resource::CreateExtendableResourceError::unhandled)?;
        crate::operation::create_extendable_resource::CreateExtendableResource::send(
            &self.client,
            input,
        )
        .await
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.name(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_name(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_name()
    }
}
