# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.integer

PROJECT_SERVICES := \
	SimpleInteger

SERVICE_NAMESPACE_SimpleInteger=simple.types.integer

SERVICE_DEPS_SimpleInteger :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

GO_MODULE_NAME="github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger"

PROJECT_DTR := \
    dafny-dependencies/StandardLibrary/runtimes/go/ImplementationFromDafny-go/ImplementationFromDafny-go.dtr
# This project has no dependencies
# DEPENDENT-MODELS:=

