# Code generated by smithy-python-codegen DO NOT EDIT.

from simple.types.integer.internaldafny.types import (
    GetIntegerKnownValueTestOutput_GetIntegerKnownValueTestOutput as DafnyGetIntegerKnownValueTestOutput,
    GetIntegerOperationOutput_GetIntegerOperationOutput as DafnyGetIntegerOperationOutput,
)

from .config import Config
from .models import GetIntegerKnownValueTestOutput, GetIntegerOperationOutput


async def _deserialize_get_integer(input: DafnyGetIntegerOperationOutput, config: Config) -> GetIntegerOperationOutput:

  return GetIntegerOperationOutput(value=input.value.value)

async def _deserialize_get_integer_known_value_test(input: DafnyGetIntegerKnownValueTestOutput, config: Config) -> GetIntegerKnownValueTestOutput:

  return GetIntegerKnownValueTestOutput(value=input.value.value)
