# Code generated by smithy-python-codegen DO NOT EDIT.

from simple.types.integer.internaldafny.types import (
    GetIntegerKnownValueTestInput_GetIntegerKnownValueTestInput as DafnyGetIntegerKnownValueTestInput,
    GetIntegerOperationInput_GetIntegerOperationInput as DafnyGetIntegerOperationInput,
)

from .config import Config
from .models import GetIntegerKnownValueTestInput, GetIntegerOperationInput


async def _serialize_get_integer(input: GetIntegerOperationInput, config: Config) -> DafnyGetIntegerOperationInput:
    return ("GetInteger", DafnyGetIntegerOperationInput(value=input.value))

async def _serialize_get_integer_known_value_test(input: GetIntegerKnownValueTestInput, config: Config) -> DafnyGetIntegerKnownValueTestInput:
    return ("GetIntegerKnownValueTest", DafnyGetIntegerKnownValueTestInput(value=input.value))
