# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.timestamp

PROJECT_SERVICES := \
	SimpleTypesTimestamp

SERVICE_NAMESPACE_SimpleTypesTimestamp=simple.types.timestamp

SERVICE_DEPS_SimpleTypesTimestamp :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies 
# DEPENDENT-MODELS:= 


POLYMORPH_OPTIONS=--generate client-externs --generate project-files --generate impl-stub
