// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/// Orchestration and serialization glue logic for `AlwaysModeledError`.

#[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct AlwaysModeledError;
impl AlwaysModeledError {
    /// Uses a new `AlwaysModeledError`
    pub fn new() -> Self {
        Self
    }
    pub(crate) async fn send(
        client: crate::types::extendable_resource::ExtendableResourceRef,
        input: crate::operation::always_modeled_error::AlwaysModeledErrorInput,
    ) -> ::std::result::Result<
        crate::operation::always_modeled_error::AlwaysModeledErrorOutput,
        crate::operation::always_modeled_error::AlwaysModeledErrorError,
    > {
        client.borrow_mut().always_modeled_error(input)
    }
}

/// Error type for the `AlwaysModeledError` operation.
#[non_exhaustive]
#[derive(::std::fmt::Debug)]
pub enum AlwaysModeledErrorError {
    SimpleExtendableResourcesException(
        crate::error::simple_extendable_resources_exception::SimpleExtendableResourcesException,
    ),
    /// An unexpected error occurred (e.g., invalid JSON returned by the service or an unknown error code).
    Unhandled(crate::error::sealed_unhandled::Unhandled),
}
impl AlwaysModeledErrorError {
    /// Uses the `AlwaysModeledErrorError::Unhandled` variant from any error type.
    pub fn unhandled(
        err: impl ::std::convert::Into<
            ::std::boxed::Box<
                dyn ::std::error::Error + ::std::marker::Send + ::std::marker::Sync + 'static,
            >,
        >,
    ) -> Self {
        Self::Unhandled(crate::error::sealed_unhandled::Unhandled {
            source: err.into(),
            meta: ::std::default::Default::default(),
        })
    }

    /// Uses the `AlwaysModeledErrorError::Unhandled` variant from an [`ErrorMetadata`](::aws_smithy_types::error::ErrorMetadata).
    pub fn generic(err: ::aws_smithy_types::error::ErrorMetadata) -> Self {
        Self::Unhandled(crate::error::sealed_unhandled::Unhandled {
            source: err.clone().into(),
            meta: err,
        })
    }
    ///
    /// Returns error metadata, which includes the error code, message,
    /// request ID, and potentially additional information.
    ///
    pub fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata {
        match self {
            Self::SimpleExtendableResourcesException(e) => &e.meta,
            Self::Unhandled(e) => &e.meta,
        }
    }
}
impl ::std::error::Error for AlwaysModeledErrorError {
    fn source(&self) -> ::std::option::Option<&(dyn ::std::error::Error + 'static)> {
        match self {
            Self::SimpleExtendableResourcesException(_) => None,
            Self::Unhandled(_inner) => ::std::option::Option::Some(&*_inner.source),
        }
    }
}
impl ::std::fmt::Display for AlwaysModeledErrorError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::SimpleExtendableResourcesException(e) => {
                write!(f, "SimpleExtendableResourcesException : {:}", e.message)
            }
            Self::Unhandled(_inner) => {
                if let ::std::option::Option::Some(code) =
                    ::aws_smithy_types::error::metadata::ProvideErrorMetadata::code(self)
                {
                    write!(f, "unhandled error ({code})")
                } else {
                    f.write_str("unhandled error")
                }
            }
        }
    }
}
impl ::aws_smithy_types::retry::ProvideErrorKind for AlwaysModeledErrorError {
    fn code(&self) -> ::std::option::Option<&str> {
        ::aws_smithy_types::error::metadata::ProvideErrorMetadata::code(self)
    }
    fn retryable_error_kind(&self) -> ::std::option::Option<::aws_smithy_types::retry::ErrorKind> {
        ::std::option::Option::None
    }
}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for AlwaysModeledErrorError {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata {
        match self {
            Self::SimpleExtendableResourcesException(e) => &e.meta,
            Self::Unhandled(_inner) => &_inner.meta,
        }
    }
}
impl ::aws_smithy_runtime_api::client::result::CreateUnhandledError for AlwaysModeledErrorError {
    fn create_unhandled_error(
        source: ::std::boxed::Box<
            dyn ::std::error::Error + ::std::marker::Send + ::std::marker::Sync + 'static,
        >,
        meta: ::std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
    ) -> Self {
        Self::Unhandled(crate::error::sealed_unhandled::Unhandled {
            source,
            meta: meta.unwrap_or_default(),
        })
    }
}

pub use crate::operation::always_modeled_error::_always_modeled_error_output::AlwaysModeledErrorOutput;

pub use crate::operation::always_modeled_error::_always_modeled_error_input::AlwaysModeledErrorInput;

mod _always_modeled_error_input;

mod _always_modeled_error_output;

/// Builders
pub mod builders;
