// Code generated by smithy-go-codegen DO NOT EDIT.

package simplepositionaltypes

import (
	"fmt"
)

type SimplePositionalException struct {
	SimplePositionalBaseException
	Message *string

	ErrorCodeOverride *string
}

func (e SimplePositionalException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCodeOverride, e.Message)
}
