// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetKnownValueUnion`](crate::operation::get_known_value_union::builders::GetKnownValueUnionFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`union(KnownValueUnion)`](crate::operation::get_known_value_union::builders::GetKnownValueUnionFluentBuilder::union) / [`set_union(Option<KnownValueUnion>)`](crate::operation::get_known_value_union::builders::GetKnownValueUnionFluentBuilder::set_union):<br>required: **false**<br>(undocumented)<br>
    /// - On success, responds with [`GetKnownValueUnionOutput`](crate::operation::get_known_value_union::GetKnownValueUnionOutput) with field(s):
    ///   - [`union(Option<KnownValueUnion>)`](crate::operation::get_known_value_union::GetKnownValueUnionOutput::union): (undocumented)
    /// - On failure, responds with [`SdkError<GetKnownValueUnionError>`](crate::operation::get_known_value_union::GetKnownValueUnionError)
    pub fn get_union_known_value(
        &self,
    ) -> crate::operation::get_known_value_union::builders::GetKnownValueUnionFluentBuilder {
        crate::operation::get_known_value_union::builders::GetKnownValueUnionFluentBuilder::new(
            self.clone(),
        )
    }
}
