// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetUnion`](crate::operation::get_union::builders::GetUnionFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`union(MyUnion)`](crate::operation::get_union::builders::GetUnionFluentBuilder::union) / [`set_union(Option<MyUnion>)`](crate::operation::get_union::builders::GetUnionFluentBuilder::set_union):<br>required: **false**<br>(undocumented)<br>
    ///   - [`value(i32)`](crate::operation::get_union::builders::GetUnionFluentBuilder::value) / [`set_value(Option<i32>)`](crate::operation::get_union::builders::GetUnionFluentBuilder::set_value):(undocumented)<br>
    /// - On success, responds with [`GetUnionOutput`](crate::operation::get_union::GetUnionOutput) with field(s):
    ///   - [`union(Option<MyUnion>)`](crate::operation::get_union::GetUnionOutput::union): (undocumented)
    ///   - [`value(Option<Union>)`](crate::operation::get_union::GetUnionOutput::value): (undocumented)
    /// - On failure, responds with [`SdkError<GetUnionError>`](crate::operation::get_union::GetUnionError)
    pub fn get_union(&self) -> crate::operation::get_union::builders::GetUnionFluentBuilder {
        crate::operation::get_union::builders::GetUnionFluentBuilder::new(self.clone())
    }
}
