# Code generated by smithy-python-codegen DO NOT EDIT.

from .config import Config, Plugin
from smithy_python.interfaces.retries import RetryStrategy
from smithy_python.exceptions import SmithyRetryException
from .dafnyImplInterface import DafnyImplInterface

def set_config_impl(config: Config):
    from simple.refinement.internaldafny.impl import SimpleRefinementClient
    config.dafnyImplInterface = DafnyImplInterface()
    config.dafnyImplInterface.impl = SimpleRefinementClient()
    config.retry_strategy = NoRetriesStrategy()

class NoRetriesToken:
    retry_delay = 0

class NoRetriesStrategy(RetryStrategy):
    def acquire_initial_retry_token(self):
        return NoRetriesToken()

    def refresh_retry_token_for_retry(self, token_to_renew, error_info):
        # Do not retry
        raise SmithyRetryException()
