// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]
pub fn to_dafny(
    value: crate::operation::get_timestamp::GetTimestampOutput,
) -> ::std::rc::Rc<
    crate::r#simple::types::timestamp::internaldafny::types::GetTimestampOutput,
> {
    let dafny_value = match value.value {
        Some(s) => crate::_Wrappers_Compile::Option::Some { value: ::dafny_runtime::dafny_runtime_conversions::unicode_chars_false::string_to_dafny_string(&s.to_string()) },
        None => crate::_Wrappers_Compile::Option::None {},
    };
    ::std::rc::Rc::new(crate::r#simple::types::timestamp::internaldafny::types::GetTimestampOutput::GetTimestampOutput {
    value: ::std::rc::Rc::new(dafny_value)
  })
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#simple::types::timestamp::internaldafny::types::GetTimestampOutput,
    >,
) -> Result<
    crate::operation::get_timestamp::GetTimestampOutput,
    aws_smithy_types::date_time::DateTimeParseError,
> {
    let value = match dafny_value.value().as_ref() {
        crate::_Wrappers_Compile::Option::None {} => None,
        crate::_Wrappers_Compile::Option::Some { value } => {
            let value = dafny_runtime::dafny_runtime_conversions::unicode_chars_false::dafny_string_to_string(&value);
            let value = ::aws_smithy_types::DateTime::from_str(
                &value,
                aws_smithy_types::date_time::Format::DateTime,
            )?;
            Some(value)
        }
    };

    Ok(crate::operation::get_timestamp::GetTimestampOutput { value })
}
