// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Types for the `GetEnumV2` operation.
pub mod get_enum_v2;

/// Types for the `GetEnumV2KnownValue` operation.
pub mod get_enum_v2_first_known_value_test;
pub mod get_enum_v2_second_known_value_test;
pub mod get_enum_v2_third_known_value_test;
