// Code generated by smithy-go-codegen DO NOT EDIT.

package simplepositional

import (
	"github.com/Smithy-dafny/TestModels/Positional/simplepositionalinternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/Positional/simplepositionaltypes"
)

type SimpleResource struct {
	Impl simplepositionalinternaldafnytypes.ISimpleResource
}

func (this *SimpleResource) GetName(params simplepositionaltypes.GetNameInput) (*simplepositionaltypes.GetNameOutput, error) {
	var dafny_request simplepositionalinternaldafnytypes.GetNameInput = GetNameInput_ToDafny(params)
	var dafny_response = this.Impl.GetName(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simplepositionalinternaldafnytypes.Error)
		if err.Is_SimplePositionalException() {
			return nil, SimplePositionalException_FromDafny(err)
		}

		if err.Is_CollectionOfErrors() {
			return nil, CollectionOfErrors_Output_FromDafny(err)
		}
		if err.Is_Opaque() {
			return nil, OpaqueError_Output_FromDafny(err)
		}
	}
	var native_response = GetNameOutput_FromDafny(dafny_response.Extract().(simplepositionalinternaldafnytypes.GetNameOutput))
	return &native_response, nil

}
