# Code generated by smithy-python-codegen DO NOT EDIT.

import smithygenerated.simple_dafnyexternv2.config
import smithygenerated.simple_dafnyexternv2.models


def DafnyToSmithy_simple_dafnyexternv2_GetExternV2Input(input):
    return smithygenerated.simple_dafnyexternv2.models.GetExternV2Input(
        blob_value=(bytes(input.blobValue.value)) if (input.blobValue.is_Some) else None,
        boolean_value=(input.booleanValue.value) if (input.booleanValue.is_Some) else None,
        string_value=(input.stringValue.value.VerbatimString(False)) if (input.stringValue.is_Some) else None,
        integer_value=(input.integerValue.value) if (input.integerValue.is_Some) else None,
        long_value=(input.longValue.value) if (input.longValue.is_Some) else None,
    )

def DafnyToSmithy_simple_dafnyexternv2_UseClassExternV2Input(input):
    return smithygenerated.simple_dafnyexternv2.models.UseClassExternV2Input(
        value=(input.value.value.VerbatimString(False)) if (input.value.is_Some) else None,
    )

def DafnyToSmithy_simple_dafnyexternv2_ExternV2MustErrorInput(input):
    return smithygenerated.simple_dafnyexternv2.models.ExternV2MustErrorInput(
        value=(input.value.value.VerbatimString(False)) if (input.value.is_Some) else None,
    )

def DafnyToSmithy_simple_dafnyexternv2_GetExternV2Output(input):
    return smithygenerated.simple_dafnyexternv2.models.GetExternV2Output(
        blob_value=(bytes(input.blobValue.value)) if (input.blobValue.is_Some) else None,
        boolean_value=(input.booleanValue.value) if (input.booleanValue.is_Some) else None,
        string_value=(input.stringValue.value.VerbatimString(False)) if (input.stringValue.is_Some) else None,
        integer_value=(input.integerValue.value) if (input.integerValue.is_Some) else None,
        long_value=(input.longValue.value) if (input.longValue.is_Some) else None,
    )

def DafnyToSmithy_simple_dafnyexternv2_UseClassExternV2Output(input):
    return smithygenerated.simple_dafnyexternv2.models.UseClassExternV2Output(
        value=(input.value.value.VerbatimString(False)) if (input.value.is_Some) else None,
    )

def DafnyToSmithy_simple_dafnyexternv2_ExternV2MustErrorOutput(input):
    return smithygenerated.simple_dafnyexternv2.models.ExternV2MustErrorOutput(
        value=(input.value.value.VerbatimString(False)) if (input.value.is_Some) else None,
    )

def DafnyToSmithy_simple_dafnyexternv2_SimpleExternV2Config(input):
    return smithygenerated.simple_dafnyexternv2.config.SimpleExternV2Config(
    )
