# Code generated by smithy-python-codegen DO NOT EDIT.

import module_
import simple_types_smithyenum.smithygenerated.simple_types_smithyenum.dafny_to_smithy
import simple_types_smithyenum.smithygenerated.simple_types_smithyenum.models
import simple_types_smithyenum.smithygenerated.simple_types_smithyenum.smithy_to_dafny
from simple_types_smithyenum_internaldafny_types import (
    GetEnumInput_GetEnumInput as DafnyGetEnumInput,
    GetEnumOutput_GetEnumOutput as DafnyGetEnumOutput,
)
from typing import Any

from .errors import (
    CollectionOfErrors,
    OpaqueError,
    ServiceError,
    _smithy_error_to_dafny_error,
)


import Wrappers
import simple_types_smithyenum_internaldafny_types
import simple_types_smithyenum.smithygenerated.simple_types_smithyenum.client as client_impl

class SimpleEnumShim(simple_types_smithyenum_internaldafny_types.ISimpleTypesEnumClient):
    def __init__(self, _impl: client_impl) :
        self._impl = _impl

    def GetEnum(self, input):
        smithy_client_request: simple_types_smithyenum.smithygenerated.simple_types_smithyenum.models.GetEnumInput = simple_types_smithyenum.smithygenerated.simple_types_smithyenum.dafny_to_smithy.simple_types_smithyenum_GetEnumInput(input)
        try:
            smithy_client_response = self._impl.get_enum(smithy_client_request)
        except ServiceError as e:
            return Wrappers.Result_Failure(_smithy_error_to_dafny_error(e))

        return Wrappers.Result_Success(simple_types_smithyenum.smithygenerated.simple_types_smithyenum.smithy_to_dafny.simple_types_smithyenum_GetEnumOutput(smithy_client_response))

    def GetEnumFirstKnownValueTest(self, input):
        smithy_client_request: simple_types_smithyenum.smithygenerated.simple_types_smithyenum.models.GetEnumInput = simple_types_smithyenum.smithygenerated.simple_types_smithyenum.dafny_to_smithy.simple_types_smithyenum_GetEnumInput(input)
        try:
            smithy_client_response = self._impl.get_enum_first_known_value_test(smithy_client_request)
        except ServiceError as e:
            return Wrappers.Result_Failure(_smithy_error_to_dafny_error(e))

        return Wrappers.Result_Success(simple_types_smithyenum.smithygenerated.simple_types_smithyenum.smithy_to_dafny.simple_types_smithyenum_GetEnumOutput(smithy_client_response))

    def GetEnumSecondKnownValueTest(self, input):
        smithy_client_request: simple_types_smithyenum.smithygenerated.simple_types_smithyenum.models.GetEnumInput = simple_types_smithyenum.smithygenerated.simple_types_smithyenum.dafny_to_smithy.simple_types_smithyenum_GetEnumInput(input)
        try:
            smithy_client_response = self._impl.get_enum_second_known_value_test(smithy_client_request)
        except ServiceError as e:
            return Wrappers.Result_Failure(_smithy_error_to_dafny_error(e))

        return Wrappers.Result_Success(simple_types_smithyenum.smithygenerated.simple_types_smithyenum.smithy_to_dafny.simple_types_smithyenum_GetEnumOutput(smithy_client_response))

    def GetEnumThirdKnownValueTest(self, input):
        smithy_client_request: simple_types_smithyenum.smithygenerated.simple_types_smithyenum.models.GetEnumInput = simple_types_smithyenum.smithygenerated.simple_types_smithyenum.dafny_to_smithy.simple_types_smithyenum_GetEnumInput(input)
        try:
            smithy_client_response = self._impl.get_enum_third_known_value_test(smithy_client_request)
        except ServiceError as e:
            return Wrappers.Result_Failure(_smithy_error_to_dafny_error(e))

        return Wrappers.Result_Success(simple_types_smithyenum.smithygenerated.simple_types_smithyenum.smithy_to_dafny.simple_types_smithyenum_GetEnumOutput(smithy_client_response))
