// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]

pub fn to_dafny(
    value: crate::types::simple_string_config::SimpleStringConfig,
) -> ::std::rc::Rc<
    crate::simple::types::smithystring::internaldafny::types::SimpleStringConfig,
> {
    ::std::rc::Rc::new(crate::r#simple::types::smithystring::internaldafny::types::SimpleStringConfig::SimpleStringConfig {})
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#simple::types::smithystring::internaldafny::types::SimpleStringConfig,
    >,
) -> crate::types::simple_string_config::SimpleStringConfig {
    crate::types::simple_string_config::SimpleStringConfig {}
}
