// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]
pub fn to_dafny(
    value: crate::operation::get_resource::GetResourceInput,
) -> ::std::rc::Rc<
    crate::implementation_from_dafny::r#_simple_dpositional_dinternaldafny_dtypes::GetResourceInput,
> {
    let dafny_value = match value.value {
        Some(b) => crate::implementation_from_dafny::_Wrappers_Compile::Option::Some { value: b },
        None => crate::implementation_from_dafny::_Wrappers_Compile::Option::None {},
    };
    ::std::rc::Rc::new(crate::implementation_from_dafny::r#_simple_dpositional_dinternaldafny_dtypes::GetResourceInput::GetResourceInput {

        
        name: (),
        })
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::implementation_from_dafny::r#_simple_dpositional_dinternaldafny_dtypes::GetResourceInput,
    >,
) -> crate::operation::get_resource::GetResourceInput {
    let value = if matches!(
        dafny_value.value().as_ref(),
        crate::implementation_from_dafny::_Wrappers_Compile::Option::Some { .. }
    ) {
        Some(dafny_value.value().Extract())
    } else if matches!(
        dafny_value.value().as_ref(),
        crate::implementation_from_dafny::_Wrappers_Compile::Option::None { .. }
    ) {
        None
    } else {
        panic!("Unreachable")
    };
    crate::operation::get_resource::GetResourceInput { name: ()  }
}
