// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]

pub fn to_dafny(
    value: crate::types::simple_enum_v2_config::SimpleEnumV2Config,
) -> ::std::rc::Rc<
    crate::simple::types::enumv2::internaldafny::types::SimpleEnumV2Config,
> {
    ::std::rc::Rc::new(crate::r#simple::types::enumv2::internaldafny::types::SimpleEnumV2Config::SimpleEnumV2Config {})
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#simple::types::enumv2::internaldafny::types::SimpleEnumV2Config,
    >,
) -> crate::types::simple_enum_v2_config::SimpleEnumV2Config {
    crate::types::simple_enum_v2_config::SimpleEnumV2Config {}
}
