# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../../SharedMakefile.mk

NAMESPACE=simple.types.double

# This project has no dependencies 
# DEPENDENT-MODELS:= 
# LIBRARIES :=
transpile_net_dependencies:

format_net:
	pushd runtimes/net && dotnet format && popd
