// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Types for the `SimpleResource`
pub mod simple_resource;
pub use simple_resource::SimpleResource;

/// Types for the `SimpleResourcesConfig`
pub mod simple_resources_config;
