# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../SharedMakefile.mk

NAMESPACE=simple.streaming

# TODO-Python-PYTHONPATH: Move into dfyproject.toml
PYTHON_MODULE_NAME=simple_streaming

PROJECT_SERVICES := \
        SimpleStreaming

SERVICE_NAMESPACE_SimpleStreaming=simple.streaming

SERVICE_DEPS_SimpleStreaming :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies
# DEPENDENT-MODELS:=
