# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../SharedMakefile.mk

NAMESPACE=simple.streaming

PROJECT_SERVICES := \
	Streaming

SERVICE_NAMESPACE_Streaming=simple.streaming

SERVICE_DEPS_Streaming :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies 
# DEPENDENT-MODELS:= 
