// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Types for the `GetInteger` operation.
pub mod get_integer;

/// Types for the `GetIntegerKnownValueTest` operation.
pub mod get_integer_known_value_test;
