// Code generated by smithy-go-codegen DO NOT EDIT.

package simplecallingawssdkfromlocalservicesmithygenerated

import (
	"github.com/dafny-lang/DafnyRuntimeGo/dafny"
	"github.com/smithy-lang/smithy-dafny/TestModels/CallingAWSSDKFromLocalService/SimpleCallingawssdkfromlocalserviceTypes"
	"github.com/smithy-lang/smithy-dafny/TestModels/CallingAWSSDKFromLocalService/simplecallingawssdkfromlocalservicesmithygeneratedtypes"
	"github.com/smithy-lang/smithy-dafny/kms/comamazonawskmssmithygenerated"
)

func CallKMSEncryptInput_FromDafny(dafnyInput SimpleCallingawssdkfromlocalserviceTypes.CallKMSEncryptInput) simplecallingawssdkfromlocalservicesmithygeneratedtypes.CallKMSEncryptInput {

	return simplecallingawssdkfromlocalservicesmithygeneratedtypes.CallKMSEncryptInput{KmsClient: dafnyInput.Dtor_kmsClient(), KeyId: func() string {
		var s string
		for i := dafny.Iterate(dafnyInput.Dtor_keyId()); ; {
			val, ok := i()
			if !ok {
				return s
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}(), Plaintext: func() []byte {
		var b []byte
		if dafnyInput.Dtor_plaintext() == nil {
			return nil
		}
		for i := dafny.Iterate(dafnyInput.Dtor_plaintext()); ; {
			val, ok := i()
			if !ok {
				return b
			} else {
				b = append(b, val.(byte))
			}
		}
	}()}

}

func CallKMSEncryptOutput_FromDafny(dafnyOutput SimpleCallingawssdkfromlocalserviceTypes.CallKMSEncryptOutput) simplecallingawssdkfromlocalservicesmithygeneratedtypes.CallKMSEncryptOutput {

	return simplecallingawssdkfromlocalservicesmithygeneratedtypes.CallKMSEncryptOutput{EncryptOutput: func() string {
		var s string
		for i := dafny.Iterate(dafnyOutput.Dtor_encryptOutput()); ; {
			val, ok := i()
			if !ok {
				return s
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}()}

}

func SimpleCallingAWSSDKFromLocalServiceException_FromDafny(dafnyOutput SimpleCallingawssdkfromlocalserviceTypes.Error) simplecallingawssdkfromlocalservicesmithygeneratedtypes.SimpleCallingAWSSDKFromLocalServiceException {
	return simplecallingawssdkfromlocalservicesmithygeneratedtypes.SimpleCallingAWSSDKFromLocalServiceException{Message: func() string {
		var s string
		for i := dafny.Iterate(dafnyOutput.Dtor_message()); ; {
			val, ok := i()
			if !ok {
				return s
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}()}

}

func CollectionOfErrors_Output_FromDafny(dafnyOutput SimpleCallingawssdkfromlocalserviceTypes.Error) simplecallingawssdkfromlocalservicesmithygeneratedtypes.CollectionOfErrors {
	listOfErrors := dafnyOutput.Dtor_list()
	message := dafnyOutput.Dtor_message()
	t := simplecallingawssdkfromlocalservicesmithygeneratedtypes.CollectionOfErrors{}
	for i := dafny.Iterate(listOfErrors); ; {
		val, ok := i()
		if !ok {
			break
		}
		err := val.(SimpleCallingawssdkfromlocalserviceTypes.Error)
		t.ListOfErrors = append(t.ListOfErrors, Error_FromDafny(err))

	}
	t.Message = func() string {
		var s string
		for i := dafny.Iterate(message); ; {
			val, ok := i()
			if !ok {
				return s
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}()
	return t
}
func OpaqueError_Output_FromDafny(dafnyOutput SimpleCallingawssdkfromlocalserviceTypes.Error) simplecallingawssdkfromlocalservicesmithygeneratedtypes.OpaqueError {
	return simplecallingawssdkfromlocalservicesmithygeneratedtypes.OpaqueError{
		ErrObject: dafnyOutput.Dtor_obj(),
	}
}

func Error_FromDafny(err SimpleCallingawssdkfromlocalserviceTypes.Error) error {
	// Service Errors
	if err.Is_SimpleCallingAWSSDKFromLocalServiceException() {
		return SimpleCallingAWSSDKFromLocalServiceException_FromDafny(err)
	}

	//DependentErrors

	//Unmodelled Errors
	if err.Is_CollectionOfErrors() {
		return CollectionOfErrors_Output_FromDafny(err)
	}

	return OpaqueError_Output_FromDafny(err)
}

func SimpleCallingAWSSDKFromLocalServiceConfig_FromDafny(dafnyOutput SimpleCallingawssdkfromlocalserviceTypes.SimpleCallingAWSSDKFromLocalServiceConfig) simplecallingawssdkfromlocalservicesmithygeneratedtypes.SimpleCallingAWSSDKFromLocalServiceConfig {
	return simplecallingawssdkfromlocalservicesmithygeneratedtypes.SimpleCallingAWSSDKFromLocalServiceConfig{}

}
