// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]
pub fn to_dafny(
    value: crate::operation::get_runtime_information::GetRuntimeInformationOutput,
) -> ::std::rc::Rc<
    crate::r#language::specific::logic::internaldafny::types::GetRuntimeInformationOutput,
> {
    let crate::operation::get_runtime_information::GetRuntimeInformationOutput {
        language,
        runtime,
    } = value;

    let language =
        dafny_runtime::dafny_runtime_conversions::unicode_chars_false::string_to_dafny_string(
            &language,
        );

    let runtime =
        dafny_runtime::dafny_runtime_conversions::unicode_chars_false::string_to_dafny_string(
            &runtime,
        );

    ::std::rc::Rc::new(crate::r#language::specific::logic::internaldafny::types::GetRuntimeInformationOutput::GetRuntimeInformationOutput {
        language: language,
        runtime: runtime,
  })
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<crate::r#language::specific::logic::internaldafny::types::GetRuntimeInformationOutput>,
) -> crate::operation::get_runtime_information::GetRuntimeInformationOutput {
    let crate::r#language::specific::logic::internaldafny::types::GetRuntimeInformationOutput::GetRuntimeInformationOutput { language, runtime } = dafny_value.as_ref();

    let language =
        dafny_runtime::dafny_runtime_conversions::unicode_chars_false::dafny_string_to_string(
            &language,
        );

    let runtime =
        dafny_runtime::dafny_runtime_conversions::unicode_chars_false::dafny_string_to_string(
            &runtime,
        );

    crate::operation::get_runtime_information::GetRuntimeInformationOutput {
        language,
        runtime,
    }
}
