// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetResources`](crate::operation::get_resources::builders::GetResourcesFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`value(impl Into<Option<Resources>>)`](crate::operation::get_resources::builders::GetResourcesFluentBuilder::name) / [`set_name(Option<Resources>)`](crate::operation::get_resources::builders::GetResourcesFluentBuilder::set_name):(undocumented)<br>
    /// - On success, responds with [`GetResourcesOutput`](crate::operation::get_resources::GetResourcesOutput) with field(s):
    ///   - [`value(Option<Resources>)`](crate::operation::get_resources::GetResourcesOutput::value): (undocumented)
    /// - On failure, responds with [`SdkError<GetResourcesError>`](crate::operation::get_resources::GetResourcesError)
    pub fn get_resources(&self) -> crate::operation::get_resources::builders::GetResourcesFluentBuilder {
        crate::operation::get_resources::builders::GetResourcesFluentBuilder::new(self.clone())
    }
}
