# Code generated by smithy-python-codegen DO NOT EDIT.

from Dafny.Path.To.Dafny.Code. import SimpleBooleanHardCoded as _SimpleBooleanHardCoded
from smithy_python.interfaces.http import IaAmDafny

from .config import Config
from .models import GetBooleanInput


async def _serialize_get_boolean(input: GetBooleanInput, config: Config) -> IaAmDafny:
    return _SimpleBooleanHardCoded.get_boolean()
