// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]

pub fn to_dafny(
    value: crate::types::simple_blob_config::SimpleBlobConfig,
) -> ::std::rc::Rc<crate::simple::types::blob::internaldafny::types::SimpleBlobConfig>
{
    ::std::rc::Rc::new(crate::r#simple::types::blob::internaldafny::types::SimpleBlobConfig::SimpleBlobConfig {})
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#simple::types::blob::internaldafny::types::SimpleBlobConfig,
    >,
) -> crate::types::simple_blob_config::SimpleBlobConfig {
    crate::types::simple_blob_config::SimpleBlobConfig {}
}
