// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetLongKnownValueInput {
    #[allow(missing_docs)] // documentation missing in model
    pub value: ::std::option::Option<i64>,
}
impl GetLongKnownValueInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn value(&self) -> ::std::option::Option<i64> {
        self.value
    }
}
impl GetLongKnownValueInput {
    /// Creates a new builder-style object to manufacture [`GetLongKnownValueInput`](crate::operation::operation::GetLongKnownValueInput).
    pub fn builder(
    ) -> crate::operation::get_long_known_value::builders::GetLongKnownValueInputBuilder {
        crate::operation::get_long_known_value::builders::GetLongKnownValueInputBuilder::default()
    }
}

/// A builder for [`GetLongKnownValueInput`](crate::operation::operation::GetLongKnownValueInput).
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
pub struct GetLongKnownValueInputBuilder {
    pub(crate) value: ::std::option::Option<i64>,
}
impl GetLongKnownValueInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn value(
        mut self,
        input: impl ::std::convert::Into<i64>,
    ) -> Self {
        self.value = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_value(
        mut self,
        input: ::std::option::Option<i64>,
    ) -> Self {
        self.value = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_value(&self) -> &::std::option::Option<i64> {
        &self.value
    }
    /// Consumes the builder and constructs a [`GetLongKnownValueInput`](crate::operation::operation::GetLongKnownValueInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_long_known_value::GetLongKnownValueInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::get_long_known_value::GetLongKnownValueInput { value: self.value },
        )
    }
}
