# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

RUST_BENERATED=1

include ../../SharedMakefile.mk

NAMESPACE=simple.types.blob

PROJECT_SERVICES := \
	SimpleBlob

SERVICE_NAMESPACE_SimpleBlob=simple.types.blob

SERVICE_DEPS_SimpleBlob :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies 
# DEPENDENT-MODELS:= 
