// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]
pub fn to_dafny(
    value: crate::operation::always_modeled_error::AlwaysModeledErrorInput,
) -> ::std::rc::Rc<
    ::simple_extendable_dafny::r#_simple_dextendable_dresources_dinternaldafny_dtypes::GetExtendableResourceErrorsInput,
>{
    ::std::rc::Rc::new(::simple_extendable_dafny::r#_simple_dextendable_dresources_dinternaldafny_dtypes::GetExtendableResourceErrorsInput::GetExtendableResourceErrorsInput {
        value: dafny_standard_library::conversion::ostring_to_dafny(value.value()),
  })
}
// _always_modeled_error_Input
#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        ::simple_extendable_dafny::r#_simple_dextendable_dresources_dinternaldafny_dtypes::GetExtendableResourceErrorsInput,
    >,
) -> crate::operation::always_modeled_error::AlwaysModeledErrorInput {
    match &*dafny_value {
        ::simple_extendable_dafny::r#_simple_dextendable_dresources_dinternaldafny_dtypes::GetExtendableResourceErrorsInput::GetExtendableResourceErrorsInput {
            value,
        } =>
        crate::operation::always_modeled_error::AlwaysModeledErrorInput {
            value: dafny_standard_library::conversion::ostring_from_dafny(value.clone()),
        }
    }
}
