// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[allow(dead_code)]
pub fn to_dafny(
    value: &aws_sdk_dynamodb::types::ExpectedAttributeValue,
) -> ::std::rc::Rc<crate::implementation_from_dafny::r#_software_damazon_dcryptography_dservices_ddynamodb_dinternaldafny_dtypes::ExpectedAttributeValue>{
  ::std::rc::Rc::new(
    crate::implementation_from_dafny::r#_software_damazon_dcryptography_dservices_ddynamodb_dinternaldafny_dtypes::ExpectedAttributeValue::ExpectedAttributeValue {
        Value: todo!(),
 Exists: dafny_standard_library::conversion::obool_to_dafny(&value.exists),
 ComparisonOperator: ::std::rc::Rc::new(match &value.comparison_operator {
    Some(x) => crate::implementation_from_dafny::_Wrappers_Compile::Option::Some { value: crate::conversions::comparison_operator::to_dafny(x.clone()) },
    None => crate::implementation_from_dafny::_Wrappers_Compile::Option::None { }
})
,
 AttributeValueList: todo!(),
    }
  )
} #[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::implementation_from_dafny::r#_software_damazon_dcryptography_dservices_ddynamodb_dinternaldafny_dtypes::ExpectedAttributeValue,
    >,
) -> aws_sdk_dynamodb::types::ExpectedAttributeValue {
    aws_sdk_dynamodb::types::ExpectedAttributeValue::builder()
          .set_value(todo!())
 .set_exists(dafny_standard_library::conversion::obool_from_dafny(dafny_value.Exists().clone()))
 .set_comparison_operator(match &**dafny_value.ComparisonOperator() {
    crate::implementation_from_dafny::r#_Wrappers_Compile::Option::Some { value } => Some(
        crate::conversions::comparison_operator::from_dafny(value)
    ),
    _ => None,
}
)
 .set_attribute_value_list(todo!())
          .build()
}
