// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Do not modify this file. This file is machine generated, and any changes to it will be overwritten.
// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[allow(dead_code)]
pub fn to_dafny(
    value: &aws_sdk_dynamodb::types::StreamSpecification,
) -> ::std::rc::Rc<crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::StreamSpecification>{
  ::std::rc::Rc::new(
    crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::StreamSpecification::StreamSpecification {
        StreamEnabled: crate::standard_library_conversions::obool_to_dafny(value.stream_enabled),
 StreamViewType: ::std::rc::Rc::new(match &value.stream_view_type {
    Some(x) => crate::_Wrappers_Compile::Option::Some { value: crate::conversions::stream_view_type::to_dafny(x.clone()) },
    None => crate::_Wrappers_Compile::Option::None { }
})
,
    }
  )
} #[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#software::amazon::cryptography::services::dynamodb::internaldafny::types::StreamSpecification,
    >,
) -> aws_sdk_dynamodb::types::StreamSpecification {
    aws_sdk_dynamodb::types::StreamSpecification::builder()
          .set_stream_enabled(crate::standard_library_conversions::obool_from_dafny(dafny_value.StreamEnabled().clone()))
 .set_stream_view_type(match &**dafny_value.StreamViewType() {
    crate::r#_Wrappers_Compile::Option::Some { value } => Some(
        crate::conversions::stream_view_type::from_dafny(value)
    ),
    _ => None,
}
)
          .build()

}
