// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]
pub fn to_dafny(
    value: crate::operation::get_resource_data::GetResourceDataOutput,
) -> ::std::rc::Rc<
    crate::r#simple::resources::internaldafny::types::GetResourceDataOutput,
> {
    ::std::rc::Rc::new(crate::r#simple::resources::internaldafny::types::GetResourceDataOutput::GetResourceDataOutput {
        stringValue: crate::standard_library_conversions::ostring_to_dafny(value.string_value()),
        booleanValue: crate::standard_library_conversions::obool_to_dafny(value.boolean_value()),
        integerValue: crate::standard_library_conversions::oint_to_dafny(value.integer_value()),
        longValue: crate::standard_library_conversions::olong_to_dafny(value.long_value()),
        blobValue: crate::standard_library_conversions::oblob_to_dafny(value.blob_value())
  })
}
// _get_resource_data_output
#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#simple::resources::internaldafny::types::GetResourceDataOutput,
    >,
) -> crate::operation::get_resource_data::GetResourceDataOutput {
    match &*dafny_value {
        crate::r#simple::resources::internaldafny::types::GetResourceDataOutput::GetResourceDataOutput {
            blobValue,
            booleanValue,
            integerValue,
            longValue,
            stringValue,
        } =>
        crate::operation::get_resource_data::GetResourceDataOutput {
            string_value: crate::standard_library_conversions::ostring_from_dafny(stringValue.clone()),
            boolean_value: crate::standard_library_conversions::obool_from_dafny(booleanValue.clone()),
            integer_value: crate::standard_library_conversions::oint_from_dafny(integerValue.clone()),
            long_value: crate::standard_library_conversions::olong_from_dafny(longValue.clone()),
            blob_value: crate::standard_library_conversions::oblob_from_dafny(blobValue.clone())
         }
    }
}
