# Code generated by smithy-python-codegen DO NOT EDIT.

from software_amazon_cryptography_services_kms_internaldafny_types import (
    CancelKeyDeletionRequest_CancelKeyDeletionRequest as DafnyCancelKeyDeletionRequest,
    ConnectCustomKeyStoreRequest_ConnectCustomKeyStoreRequest as DafnyConnectCustomKeyStoreRequest,
    CreateAliasRequest_CreateAliasRequest as DafnyCreateAliasRequest,
    CreateCustomKeyStoreRequest_CreateCustomKeyStoreRequest as DafnyCreateCustomKeyStoreRequest,
    CreateGrantRequest_CreateGrantRequest as DafnyCreateGrantRequest,
    CreateKeyRequest_CreateKeyRequest as DafnyCreateKeyRequest,
    DecryptRequest_DecryptRequest as DafnyDecryptRequest,
    DeleteAliasRequest_DeleteAliasRequest as DafnyDeleteAliasRequest,
    DeleteCustomKeyStoreRequest_DeleteCustomKeyStoreRequest as DafnyDeleteCustomKeyStoreRequest,
    DeleteImportedKeyMaterialRequest_DeleteImportedKeyMaterialRequest as DafnyDeleteImportedKeyMaterialRequest,
    DescribeCustomKeyStoresRequest_DescribeCustomKeyStoresRequest as DafnyDescribeCustomKeyStoresRequest,
    DescribeKeyRequest_DescribeKeyRequest as DafnyDescribeKeyRequest,
    DisableKeyRequest_DisableKeyRequest as DafnyDisableKeyRequest,
    DisableKeyRotationRequest_DisableKeyRotationRequest as DafnyDisableKeyRotationRequest,
    DisconnectCustomKeyStoreRequest_DisconnectCustomKeyStoreRequest as DafnyDisconnectCustomKeyStoreRequest,
    EnableKeyRequest_EnableKeyRequest as DafnyEnableKeyRequest,
    EnableKeyRotationRequest_EnableKeyRotationRequest as DafnyEnableKeyRotationRequest,
    EncryptRequest_EncryptRequest as DafnyEncryptRequest,
    GenerateDataKeyPairRequest_GenerateDataKeyPairRequest as DafnyGenerateDataKeyPairRequest,
    GenerateDataKeyPairWithoutPlaintextRequest_GenerateDataKeyPairWithoutPlaintextRequest as DafnyGenerateDataKeyPairWithoutPlaintextRequest,
    GenerateDataKeyRequest_GenerateDataKeyRequest as DafnyGenerateDataKeyRequest,
    GenerateDataKeyWithoutPlaintextRequest_GenerateDataKeyWithoutPlaintextRequest as DafnyGenerateDataKeyWithoutPlaintextRequest,
    GenerateRandomRequest_GenerateRandomRequest as DafnyGenerateRandomRequest,
    GetKeyPolicyRequest_GetKeyPolicyRequest as DafnyGetKeyPolicyRequest,
    GetKeyRotationStatusRequest_GetKeyRotationStatusRequest as DafnyGetKeyRotationStatusRequest,
    GetParametersForImportRequest_GetParametersForImportRequest as DafnyGetParametersForImportRequest,
    GetPublicKeyRequest_GetPublicKeyRequest as DafnyGetPublicKeyRequest,
    ImportKeyMaterialRequest_ImportKeyMaterialRequest as DafnyImportKeyMaterialRequest,
    ListAliasesRequest_ListAliasesRequest as DafnyListAliasesRequest,
    ListGrantsRequest_ListGrantsRequest as DafnyListGrantsRequest,
    ListKeyPoliciesRequest_ListKeyPoliciesRequest as DafnyListKeyPoliciesRequest,
    ListResourceTagsRequest_ListResourceTagsRequest as DafnyListResourceTagsRequest,
    PutKeyPolicyRequest_PutKeyPolicyRequest as DafnyPutKeyPolicyRequest,
    ReEncryptRequest_ReEncryptRequest as DafnyReEncryptRequest,
    ReplicateKeyRequest_ReplicateKeyRequest as DafnyReplicateKeyRequest,
    RetireGrantRequest_RetireGrantRequest as DafnyRetireGrantRequest,
    RevokeGrantRequest_RevokeGrantRequest as DafnyRevokeGrantRequest,
    ScheduleKeyDeletionRequest_ScheduleKeyDeletionRequest as DafnyScheduleKeyDeletionRequest,
    SignRequest_SignRequest as DafnySignRequest,
    TagResourceRequest_TagResourceRequest as DafnyTagResourceRequest,
    UntagResourceRequest_UntagResourceRequest as DafnyUntagResourceRequest,
    UpdateAliasRequest_UpdateAliasRequest as DafnyUpdateAliasRequest,
    UpdateCustomKeyStoreRequest_UpdateCustomKeyStoreRequest as DafnyUpdateCustomKeyStoreRequest,
    UpdateKeyDescriptionRequest_UpdateKeyDescriptionRequest as DafnyUpdateKeyDescriptionRequest,
    UpdatePrimaryRegionRequest_UpdatePrimaryRegionRequest as DafnyUpdatePrimaryRegionRequest,
    VerifyRequest_VerifyRequest as DafnyVerifyRequest,
)
import module_


import Wrappers
from typing import Union

class DafnyRequest:
    operation_name: str
    dafny_operation_input: Union[
        DafnyUpdateCustomKeyStoreRequest,
        DafnyRetireGrantRequest,
        DafnyGenerateRandomRequest,
        DafnyCreateAliasRequest,
        DafnyCreateGrantRequest,
        DafnyUpdateAliasRequest,
        DafnyGetKeyRotationStatusRequest,
        DafnyListAliasesRequest,
        DafnyPutKeyPolicyRequest,
        DafnyDecryptRequest,
        DafnyDisableKeyRotationRequest,
        DafnyReEncryptRequest,
        DafnyDeleteCustomKeyStoreRequest,
        DafnyUpdatePrimaryRegionRequest,
        DafnyGetKeyPolicyRequest,
        DafnyRevokeGrantRequest,
        DafnyListKeyPoliciesRequest,
        DafnyUpdateKeyDescriptionRequest,
        DafnyDeleteAliasRequest,
        DafnyCancelKeyDeletionRequest,
        DafnyGetPublicKeyRequest,
        DafnyImportKeyMaterialRequest,
        DafnyDescribeCustomKeyStoresRequest,
        DafnyTagResourceRequest,
        DafnyUntagResourceRequest,
        DafnyGenerateDataKeyPairRequest,
        DafnyEnableKeyRotationRequest,
        DafnyGenerateDataKeyWithoutPlaintextRequest,
        DafnyDisconnectCustomKeyStoreRequest,
        DafnyScheduleKeyDeletionRequest,
        DafnyConnectCustomKeyStoreRequest,
        DafnyListResourceTagsRequest,
        DafnyReplicateKeyRequest,
        DafnyDescribeKeyRequest,
        DafnyGenerateDataKeyRequest,
        DafnyDisableKeyRequest,
        DafnyCreateCustomKeyStoreRequest,
        DafnyGetParametersForImportRequest,
        DafnyListGrantsRequest,
        DafnyVerifyRequest,
        DafnySignRequest,
        DafnyEncryptRequest,
        DafnyCreateKeyRequest,
        DafnyDeleteImportedKeyMaterialRequest,
        DafnyEnableKeyRequest,
        DafnyGenerateDataKeyPairWithoutPlaintextRequest,
    ]

    def __init__(self, operation_name, dafny_operation_input):
        self.operation_name = operation_name
        self.dafny_operation_input = dafny_operation_input

class DafnyResponse(Wrappers.Result):
    def __init__(self):
        super.__init__(self)
