// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`AlwaysError`](crate::operation::always_error::builders::AlwaysErrorFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`value(impl Into<Option<String>>)`](crate::operation::always_error::builders::AlwaysErrorFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::always_error::builders::AlwaysErrorFluentBuilder::set_name):(undocumented)<br>
    /// - On success, responds with [`AlwaysErrorOutput`](crate::operation::always_error::AlwaysErrorOutput) with field(s):
    ///   - [`value(Option<String>)`](crate::operation::always_error::AlwaysErrorOutput::value): (undocumented)
    /// - On failure, responds with [`SdkError<AlwaysErrorError>`](crate::operation::always_error::AlwaysErrorError)
    pub fn always_error(
        &self,
    ) -> crate::operation::always_error::builders::AlwaysErrorFluentBuilder {
        crate::operation::always_error::builders::AlwaysErrorFluentBuilder::new(self.clone())
    }
}
