# Code generated by smithy-python-codegen DO NOT EDIT.

from simple.extendable.resources.internaldafny.types import (
    CreateExtendableResourceInput_CreateExtendableResourceInput as DafnyCreateExtendableResourceInput,
    UseExtendableResourceErrorsInput_UseExtendableResourceErrorsInput as DafnyUseExtendableResourceErrorsInput,
    UseExtendableResourceInput_UseExtendableResourceInput as DafnyUseExtendableResourceInput,
)


import Wrappers_Compile
from typing import Union

class DafnyRequest:
    operation_name: str
    dafny_operation_input: Union[
        DafnyCreateExtendableResourceInput,
        DafnyUseExtendableResourceInput,
        DafnyUseExtendableResourceErrorsInput,
    ]

    def __init__(self, operation_name, dafny_operation_input):
        self.operation_name = operation_name
        self.dafny_operation_input = dafny_operation_input

class DafnyResponse(Wrappers_Compile.Result):
    def __init__(self):
        super.__init__(self)
