# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

RUST_BENERATED=1

include ../../SharedMakefile.mk

NAMESPACE=simple.types.short

# This project has no dependencies 
# DEPENDENT-MODELS:= 
