// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]

pub fn to_dafny(
    value: crate::types::simple_extendable_resources_config::SimpleExtendableResourcesConfig,
) -> ::std::rc::Rc<
    crate::simple::extendable::resources::internaldafny::types::SimpleExtendableResourcesConfig,
>{
    let inner = crate::r#simple::extendable::resources::internaldafny::types::SimpleExtendableResourcesConfig::SimpleExtendableResourcesConfig {};
    ::std::rc::Rc::new(inner)
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        crate::r#simple::extendable::resources::internaldafny::types::SimpleExtendableResourcesConfig,
    >,
) -> crate::types::simple_extendable_resources_config::SimpleExtendableResourcesConfig {
    crate::types::simple_extendable_resources_config::SimpleExtendableResourcesConfig {}
}
