# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# This project has no dependencies 
# DEPENDENT-MODELS:= 

# TODO: to un-stub, remove these no-op overrides

setup_net:
polymorph_dafny:
polymorph_dotnet:
verify:
transpile_net:
dafny-reportgenerator:
test_net:
transpile_rust:
test_rust:

# TODO: to un-stub, uncomment everything below this like and set correct values

# CORES=2

# include ../SharedMakefile.mk

# NAMESPACE=stub

# PROJECT_SERVICES := \
# 	Stub

# SERVICE_NAMESPACE_Stub=stub

# SERVICE_DEPS_Stub :=

# SMITHY_DEPS=dafny-dependencies/Model/traits.smithy
