# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# This project has no dependencies 
# DEPENDENT-MODELS:= 

CORES=2

include ../SharedMakefile.mk

NAMESPACE=simple.constructor

PROJECT_SERVICES := \
	Constructor

SERVICE_NAMESPACE_Constructor=simple.constructor

SERVICE_DEPS_Constructor :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

# This project has no dependencies 
# DEPENDENT-MODELS:= 
