# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

CORES=2

include ../SharedMakefile.mk

NAMESPACE=simple.constructor

PROJECT_SERVICES := \
	SimpleConstructor

SERVICE_NAMESPACE_SimpleConstructor=simple.constructor

SERVICE_DEPS_SimpleConstructor :=

SMITHY_DEPS=dafny-dependencies/Model/traits.smithy

GO_MODULE_NAME="github.com/Smithy-dafny/TestModels/Constructor"

# This project has no dependencies 
# DEPENDENT-MODELS:= 
