// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(dead_code)]

pub fn to_dafny(
    value: crate::types::simple_boolean_config::SimpleBooleanConfig,
) -> ::std::rc::Rc<
    simple_boolean_dafny::simple::types::boolean::internaldafny::types::SimpleBooleanConfig,
> {
    ::std::rc::Rc::new(simple_boolean_dafny::r#simple::types::boolean::internaldafny::types::SimpleBooleanConfig::SimpleBooleanConfig {})
}

#[allow(dead_code)]
pub fn from_dafny(
    dafny_value: ::std::rc::Rc<
        simple_boolean_dafny::r#simple::types::boolean::internaldafny::types::SimpleBooleanConfig,
    >,
) -> crate::types::simple_boolean_config::SimpleBooleanConfig {
    crate::types::simple_boolean_config::SimpleBooleanConfig {}
}
