# Code generated by smithy-python-codegen DO NOT EDIT.

import module_
from simple_constraints_internaldafny_types import (
    GetConstraintsInput_GetConstraintsInput as DafnyGetConstraintsInput,
)
from simple_dependencies_internaldafny_types import (
    UseSimpleResourceInput_UseSimpleResourceInput as DafnyUseSimpleResourceInput,
)
from simple_extendable_resources_internaldafny_types import (
    GetExtendableResourceDataInput_GetExtendableResourceDataInput as DafnyGetExtendableResourceDataInput,
    GetExtendableResourceErrorsInput_GetExtendableResourceErrorsInput as DafnyGetExtendableResourceErrorsInput,
)
from simple_resources_internaldafny_types import (
    GetResourcesInput_GetResourcesInput as DafnyGetResourcesInput,
)


import Wrappers
from typing import Union

class DafnyRequest:
    operation_name: str
    dafny_operation_input: Union[
        DafnyGetResourcesInput,
        DafnyGetConstraintsInput,
        DafnyGetExtendableResourceErrorsInput,
        DafnyGetExtendableResourceDataInput,
        DafnyUseSimpleResourceInput,
    ]

    def __init__(self, operation_name, dafny_operation_input):
        self.operation_name = operation_name
        self.dafny_operation_input = dafny_operation_input

class DafnyResponse(Wrappers.Result):
    def __init__(self):
        super.__init__(self)
