// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetDoubleKnownValueInput {
    #[allow(missing_docs)] // documentation missing in model
    pub value: ::std::option::Option<::std::vec::Vec<::std::primitive::u8>>,
}
impl GetDoubleKnownValueInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn message(&self) -> ::std::option::Option<&::std::vec::Vec<::std::primitive::u8>> {
        self.value.as_ref()
    }
}
impl GetDoubleKnownValueInput {
    /// Creates a new builder-style object to manufacture [`GetDoubleKnownValueInput`](crate::operation::operation::GetDoubleKnownValueInput).
    pub fn builder() -> crate::operation::get_double_known_value::builders::GetDoubleKnownValueInputBuilder {
        crate::operation::get_double_known_value::builders::GetDoubleKnownValueInputBuilder::default()
    }
}

/// A builder for [`GetDoubleKnownValueInput`](crate::operation::operation::GetDoubleKnownValueInput).
#[non_exhaustive]
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
pub struct GetDoubleKnownValueInputBuilder {
    pub(crate) value: ::std::option::Option<::std::vec::Vec<::std::primitive::u8>>,
}
impl GetDoubleKnownValueInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn value(
        mut self,
        input: impl ::std::convert::Into<::std::vec::Vec<::std::primitive::u8>>,
    ) -> Self {
        self.value = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_value(
        mut self,
        input: ::std::option::Option<::std::vec::Vec<::std::primitive::u8>>,
    ) -> Self {
        self.value = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_value(&self) -> ::std::option::Option<&::std::vec::Vec<::std::primitive::u8>> {
        self.value.as_ref()
    }
    /// Consumes the builder and constructs a [`GetDoubleKnownValueInput`](crate::operation::operation::GetDoubleKnownValueInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_double_known_value::GetDoubleKnownValueInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::get_double_known_value::GetDoubleKnownValueInput { value: self.value },
        )
    }
}
